### ISSUE TITLE
When scraping Adultdvdempire VOD Scrapes don't pull actors

### ISSUE THREAD

**Issue by myxtrastufff** [Komet/MediaElch#1353] opened 2021-07-28 14:46 UTC
**Describe the bug**
When scraping Adultdvdempire VOD or Video on Demand Scrapes don't pull actors. This only appears to be an issue when picking a (VOD) movie not a (DVD) movie. But a lot of movies are only (VOD) movies

**To Reproduce**
using Adultdvdempire scraper, scrape "50 Shades Of Pink"
No actors are pulled into the tool.

**Expected behavior**
Actors are added to the tool when scraped. For "50 Shades Of Pink" the below actors are displayed on the site and should be add/pulled into the tool.
Alyssa Divine
Chantelle Fox
Holly Kiss
Seth Strong
Tiffany Naylor
Crystal Coxxx

**MediaElch Version:**
 - [ X] 2.8.12 stable

**Operating System:**
 - [ X] Windows 10

On version 2.6.4 and 2.6.6 the scraper pulls the first actor but no other actors.

**Comment by bugwelle** [comment] 2021-07-30 07:28
Thank you very much for the detailed issue report! I'll have a look in the next few days at this. :)

**Comment by Busenfreund** [comment] 2022-01-20 09:01
The majority of movies exist as DVD **and** VOD Version on ADE. For multi movie scraping it would be really helpful, if preference could be given to the DVD version in case both exist, since this bug has not been fixed yet.

Even if the bug would have been fixed, I would personally prefer to scrape the DVD version in case both exist.

**Comment by bugwelle** [comment] 2022-01-21 12:02
Ah, ok. Thanks. I forgot about this issue but have added it the v2.8.14 milestone.

**Comment by AldanaFan** [comment] 2022-01-28 12:29
Many thanks for your support!

Additionally I noticed, that the release year is not screaped correctly for some VOD movies.

Describe the bug
When scraping Adultdvdempire VOD movies, the release year is not scraped correctly for some movies. I could not clearly figure out why it works in some cases and in others it doesn't.  Maybe this happens, if the actors are not listed on ADE (like in the example below).

To Reproduce
using Adultdvdempire scraper, scrape "Titmania - Booby Style" from "Erotic Pleasure"
The release year is scraped as 2022.

Expected behavior
The release year is displayed on the site and should be 2020.

MediaElch Version:

    [ X] 2.8.12 stable

Operating System:

    [ X] Windows 10

**Comment by bugwelle** [comment] 2022-02-05 22:48
Hi,

with 709801e30a3f8ffcaf967beedd9d4cae18d00b04 and e7063d2d7ff2b83bedd5359484b7a8a1ea5c6f88 MediaElch now correctly scrapes the release date for VOD movies in the search results as well as for the movie details.

Regarding actors on VOD: I didn't find any. The movie @AldanaFan provided does not have any actors as far as I can see.

Regards,
Andre

**Comment by AldanaFan** [comment] 2022-02-06 09:54
Hi Andre,

Thanks for the update. I will check that as soon as I manage to build the project. 

One remark:
I realized that the release year is not scraped correctly, if it is not found next to the studio name on the top of the page. This is the case both for DVD and VOD movies.

DVD example: "Breast Seller 3" from "Third Degree Films"
VOD example: "Titmania - Booby Style" from "Erotic Pleasure"

In both cases the release year is not scraped correctly.

You can find the release year always on the bottom of the page under "Product Information". I would suggest to use this information, because the release year is not always given next to the studio name.

If this is already fixed with your commits above, forget what I just said ;-)

Regarding actors:
Yes, you are right. The movie I posted does not have any actors listed on ADE. It was meant as an example for the release year scraping bug.

Please use the movie @myxtrastufff posted ("50 Shades Of Pink"), then you will see the problem.

Kind regards

**Comment by bugwelle** [comment] 2022-02-06 11:29
> However, this is not the production year

Oh! Thank you very much for this insight! In https://github.com/Komet/MediaElch/commit/e7063d2d7ff2b83bedd5359484b7a8a1ea5c6f88 I set the "Released" field for ADE movies the following way:

1. If there is a `Production Year:` on the page, use that (under "Product Information" section)
2. As a fallback, use the `Released:` entry from that page (under "Product Information" section)

I hope that this pattern suits your use case. If not, let me know and I'm happy to change it.

--------------

The movie posted by  @myxtrastufff  is a good example. I've added test cases to MediaElch to check the ADE scraper for actors for this specific movie. I've also fixed the actor scraping in https://github.com/Komet/MediaElch/commit/2163843ff47aded8f78756e617858fb28cdebb2b :-)

Regards,
Andre

**Comment by AldanaFan** [comment] 2022-02-06 12:45
>In [e7063d2](https://github.com/Komet/MediaElch/commit/e7063d2d7ff2b83bedd5359484b7a8a1ea5c6f88) I set the "Released" field for ADE movies the following way:
> 
>     1. If there is a `Production Year:` on the page, use that (under "Product Information" section)
> 
>     2. As a fallback, use the `Released:` entry from that page (under "Product Information" section)

Perfect! Thank you very much!

> The movie posted by @myxtrastufff is a good example. I've added test cases to MediaElch to check the ADE scraper for actors for this specific movie. I've also fixed the actor scraping in [2163843](https://github.com/Komet/MediaElch/commit/2163843ff47aded8f78756e617858fb28cdebb2b) :-)

Awesome! Again many thanks! Would it be possible to get a compiled version with these two fixes? I'm still struggling to compile the project here on my PC.

**Comment by bugwelle** [comment] 2022-02-06 13:06
@AldanaFan I'm currently building and releasing the next MediaElch version v2.8.14. The full release process takes and hour or two. :-)

When it's ready, these links will work:

 - https://github.com/Komet/MediaElch/releases/v2.8.14
 - https://mediaelch.github.io/mediaelch-blog/posts/mediaelch-v2.8.14/

**Closed by bugwelle** 2022-02-06 13:06 UTC
Labels: bug, component: scraper

**Comment by AldanaFan** [comment] 2022-02-08 22:48
Works very well! Thank you :-)
