### ISSUE TITLE
Movie scrapers doesn't work on Linux with network error.

### ISSUE THREAD

**Issue by butty2017** [Komet/MediaElch#1117] opened 2020-12-21 08:34 UTC
**Scrapers that don't work:**
 - [X] The Movie DB
 - [X] IMDb
 - [X] OFDb
 - [ ] TMDb
 - [ ] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [X] VideoBuster

**Details which are wrong / not loaded:**
I have not succeeded in scraping. Almost all movie scrapers show "Network Error", and OFDb returns no results.

- The Movie DB, IMDb,VideoBuster: "Network Error: Could not load the requested resource"
- OFDb: "Found 0 results"

For example, failing movie info. is as follows:
- Title: "STAR WARS Episode IV" (from DVD)
- Movie directory structure and contents:
  - /media/uname/Videos/STAR WARS Episode IV/
    - VIDEO_TS/
      - VIDEO_TS.IFO, etc.

MediaElch settings:
- Scraper (Movie related)
  - Enable adult: off
  - The Movie DB: Lang.: English (US)
  - IMDb: Load all tags: off
- Movies: (all default settings)
- Network
  - Enable Proxy: off

**MediaElch Version:**
 - [X] 2.8.3-dev (nightly)
 - [X] 2.8.2 stable

Both are AppImage.

**Operating System:**
 - Linux (distribution: Linux Mint 20)

**Additional context:**
I think I am doing something wrong in MediaElch and scraping settings, or network config wrong? Would you teach me how to use the scraper if I am wrong? Or, some method to debug/trace the network error is very appreciated.

In addition, my PC can use both IPv6 and IPv4 connections. Might this config. make some problem? (Eg. If IP address obtained from name-lookup of scraper host is IPv6, MediaElch cannot handle it correctly and shows an error.) If necessary, I can disable IPv6 and retry scraping.

Thanks in advance.

**Comment by bugwelle** [comment] 2020-12-21 08:43
Hi,

the scrapers should work without any configuration. You select a movie and then click the search button. You should then see a list of movies or "No results found". The error "Network Error: Could not load the requested resource" is a general one.

Does your internet connection work? Can you visit a webpage with Firefox? Do you use a proxy?

You can start MediaElch from your console and have a look at the debug output. That has more details. Are there maybe other network errors listed? :-)

**Comment by butty2017** [comment] 2020-12-21 09:05
Hi, thanks for the reply.

Yes, I am doing just the same way as you have written. After clicking the search button (left most one) or right-clicking a movie and selecting "Load information" shows "Network Error" or no results.

Yes, my internet connection is OK (visiting here with Firefox using the same PC as MediaElch is running). Proxy is not used.

MediaElch does not show any msgs/errors on console even when failed scraping, but the following messages are shown just after started MediaElch.

> MediaElch 2020-12-21 18:02:09.654 DEBUG : [TMDb] Request setup from server
MediaElch 2020-12-21 18:02:09.662 DEBUG : [TMDb] Request setup from server
MediaElch 2020-12-21 18:02:09.666 INFO  : [TvScraper] Initializing "TMDb TV"
MediaElch 2020-12-21 18:02:09.668 INFO  : [TvScraper] Initializing "TheTvDb"
MediaElch 2020-12-21 18:02:09.669 INFO  : [TvScraper] Initializing "IMDb TV"
MediaElch 2020-12-21 18:02:09.778 DEBUG : [TMDb] Request setup from server
MediaElch 2020-12-21 18:02:09.779 DEBUG : [TMDb] Request setup from server

Note: The messages are shown after "exclude patterns:".

FYI, I'd attach MediaElch's scaping window's screenshots.

IMDb:
![Screenshot_2020-12-21_17-58-55](https://user-images.githubusercontent.com/28068190/102758537-3ce9db80-43b6-11eb-9db7-88f2114474cf.png)

OFDb(just after started scraping):
![Screenshot_2020-12-21_17-58-42](https://user-images.githubusercontent.com/28068190/102758579-4d9a5180-43b6-11eb-94a5-7c7925eed742.png)

OFDb(after some minutes):
![Screenshot_2020-12-21_17-58-05](https://user-images.githubusercontent.com/28068190/102758626-5b4fd700-43b6-11eb-9467-9e7e20305ce0.png)

**Comment by Noxx6** [comment] 2020-12-21 10:55
Hi,

I can confirm this error after updating to version 2.8.2.  I made a quick test and version 2.8.0 is still working. 

I get also the following network protocol error as soon as MediaElch tries to connect to the internet (not only the scrapers):

`MediaElch 2020-12-21 11:51:24.086 WARN  : [JsonPostRequest] Network Error: "Protocol \"https\" is unknown"`
or
`MediaElch 2020-12-21 11:51:55.605 WARN  : [IMDb] Search: Network Error "Protocol \"https\" is unknown"`

Used version: 
> MediaElch 2.8.2 - Coridian
> Compiled with Qt version 5.15.2 (64 Release, GCC 8.4.0)
> Using Qt version 5.15.2
> System: Ubuntu 20.04.1 LTS (x86_64-little_endian-lp64)

**Comment by butty2017** [comment] 2020-12-21 11:09
Hi, 

Thank you very much for the info. I tested (The Movie DB and IMDb) with 2.8.0, and scraper worked fine!

**Comment by bugwelle** [comment] 2020-12-21 12:10
Oh man. Thank you all! I'll look into it! :)

**Comment by bugwelle** [comment] 2020-12-21 12:15
hhmmm... The error that says that "openssl" is unknown may indicate an issue with openssl, see https://forum.qt.io/topic/105660/error-protocol-https-is-unknown

The latest AppImage uses Qt 5.15.2 and is built on Ubuntu 16.04. It may be that it is simply too new and may not work with the old openssl version. I can create an AppImage with Qt 5.12.4 for you to test it. Will take ~30min. :-)

I'll let you know when it's available.

**Comment by bugwelle** [comment] 2020-12-21 12:26
Ok, my internet connection is very bad. It may take longer...

**Comment by bugwelle** [comment] 2020-12-21 12:39
In the meantime I've adapted the download page: https://mediaelch.github.io/mediaelch-doc/download.html

If it is really just because of the Qt version in the AppImage, I'll simply update the AppImage. Otherwise I need to create a new release...

**Comment by bugwelle** [comment] 2020-12-21 13:00
Now available (use the one from 2020-12-21): https://bintray.com/bugwelle/MediaElch/MediaElch-Nightly/v2.8.3-dev?sort=&order=#files/

Untested because I'm on my MacBook and currently in a train. :-)

**Comment by Noxx6** [comment] 2020-12-21 13:45
> Now available (use the one from 2020-12-21): https://bintray.com/bugwelle/MediaElch/MediaElch-Nightly/v2.8.3-dev?sort=&order=#files/
> 
> Untested because I'm on my MacBook and currently in a train. :-)

Just tested it, it new works fine again! Really looks like the problem is based on the newer Qt version.
Thank you for the quick reply and your fix!

> MediaElch 2.8.3-dev - Coridian
> Compiled with Qt version 5.12.9 (64 Release, GCC 8.4.0)
> Using Qt version 5.12.9
> System: Ubuntu 20.04.1 LTS (x86_64-little_endian-lp64)

**Comment by bugwelle** [comment] 2020-12-21 15:18
Thanks! I'll update the AppImage for v2.8.2 and will then close this issue. :-)

> Have a save travel :-)

Thanks 😃

**Comment by bugwelle** [comment] 2020-12-21 15:44
AppImage is now updated for v2.8.2 😄

**Closed by bugwelle** 2020-12-21 15:44 UTC
Labels: dist: AppImage, scraper

**Comment by butty2017** [comment] 2020-12-21 22:20
Tested updated AppImage's scraper and it works well. Thank you very much!

Now, for me, MediaElch can become a good alternative to TinyMediaManager.

Thanks for your good support.

**Comment by bugwelle** [comment] 2020-12-22 10:33
Thank you for confirming it as well. Please let me know if you find any bugs. :-)
