### ISSUE TITLE
Scraping multiple titels jumbles them up

### ISSUE THREAD

**Issue by ozorfis** [Komet/MediaElch#1361] opened 2021-10-03 02:43 UTC
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ x] TMDb
 - [ ] TmdbConcert
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
When scraping a bunch of new movies at once the titles and folders get mixed up. For example: The nfo and thumbnails for movie folder D end up in movie folder B. This has happened occasionally in the past. But just now I have scraped 30 or so movies and it jumbled up every single one of them. When I scrape the folder one by one everything is fine. My library is quite large at nearly 10000 titles.

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [ x] 2.8.12 stable

**Operating System:**
 - [x ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**

**Comment by bugwelle** [comment] 2021-11-27 09:55
Hi,

thank you very much for this bug report! I'll try to reproduce this. That should __not__ happen of course. 

Regards,
Andre

**Comment by Wolli42** [comment] 2022-02-05 19:05
Hi, 
I can confirm this issue, which makes the tool currently unusable for me .. tried it with 2.8.2, 2.8.12 and 2.8.13 nightly from Jan 23. Where can I find older versions, which didn't have this bug?
Thanks and regards, 
Wolfgang

**Comment by bugwelle** [comment] 2022-02-22 19:45
Hi there,

a duplicate of this issue is #1409. I've started working on this issue. I'll provide a new nightly in the next few days when I've finally fixed this issue.

I will close this issue in favor of #1409 since I started replying there with few internal notes.

Regards,
Andre

**Closed by bugwelle** 2022-02-22 19:45 UTC
Labels: bug, priority: high
