### ISSUE TITLE
Media names containing character accents / diacritics don't save

### ISSUE THREAD

**Issue by demosthien** [Komet/MediaElch#607] opened 2018-10-04 23:22 UTC
I've got quite a few media files containing names with accents/diacritics (eg: Nausicaä and Les Misérables) and some containing punctuation marks (eg: Naples '44 A Wartime Diary) but for some reason not certain other punctuation (eg: Archer Dreamland Gramercy, Halberd!).

Mediaelch was previously accessing the files on my NAS via an SMB connection and it did not seem to have any issues with those particular files. I recently had to change the connection to my NAS to NFS and now Mediaelch constantly shows those files as needing to be scraped (despite previously already scraping and saving them and also repeatedly scraping and saving them again).

Obviously I assume this is an SMB v NFS (unfortunately I'm not sure if I can return to SMB as it was too unstable for me) issue but I thought I'd let you know in case it's something you can fix in Mediaelch.

**Comment by bugwelle** [comment] 2018-10-05 05:45
Thanks for reporting! 😄

**Comment by demosthien** [comment] 2018-10-09 19:03
Just to update with a little more info...

I tested three seperate movies.

I deleted all the extra files (ie: NFO, poster, fanart) leaving only the video itself and renamed the folder with a letter sequence (eg: ZZZ).

I then scanned the Movie folder with Mediaelch and it found the "new" files.

I scraped each file, manually typed the name of the file in the search and selecting the correct option from those provided. I saved that data and then ran the rename function.

The rename function failed (showed as red in the worklist) and an automatic rescan of the Movie folder commenced.

Each video reappeared as a "new" file and had showed the same filename as they began with and the original letter sequence folder name (eg: ZZZ) was unchanged. However, the extra files (ie: NFO, poster, fanart) had been created and saved within that folder.

**Comment by bugwelle** [comment] 2021-01-02 17:06
Hi,

we changed quite a lot in the last two years. Could you please try the latest stable version?

I tried to reproduce this but had no luck. I'm unsure how a NFS would affect MediaElch. :-/

Regards,
Andre

**Comment by psychedelys** [comment] 2023-01-01 20:03
Hi,

Well, I am on SMB and I was trying your software.
I am crossing the same issue as reported with the diacritics.
I am using version MediaElch 2.8.18 - Coridian - Linux AppImage
If I copy one movie folder on a local disk, I have exactly the same behavior. So SMB seems to be out of scope.

Regards

**Comment by bugwelle** [comment] 2023-09-30 14:28
No response in a long time. Couldn't reproduce -> closing

**Closed by bugwelle** 2023-09-30 14:28 UTC
Labels: bug, help wanted, author action
