### ISSUE TITLE
Implememt TVDB api v2

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#637] opened 2018-12-16 10:03 UTC
Since TVDB api is updated and TVDB api v1 will soon become obsolete please implement the use of api v2 in Mediaelch

Thank you

**Comment by bugwelle** [comment] 2018-12-16 11:43
We're on it. I wanted to refactor a lot, that's why it hasn't been updated, yet. :-)

Duplicate of https://github.com/Komet/MediaElch/issues/432

**Closed by bugwelle** 2018-12-16 11:43 UTC
