### ISSUE TITLE
Jungle Queen Show cannot be scrapped

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1586] opened 2023-06-20 12:55 UTC
Latest mediaelch nightly

Jungle Queen show
https://www.imdb.com/title/tt0037838/

using imdb scraper

Cannot be found.

**Comment by nkatsidis** [comment] 2023-06-20 12:55
windows version

**Comment by bugwelle** [comment] 2023-06-20 16:07
hmmm... I can reproduce it via TV show search. Using the ID `tt0037838` directly in MediaElch's tests, it scrapes all details correctly. Looking at the logs, it seems we parse some ID incorrectly:

```
 [ImdbTv] Load TV show with id: ShowIdentifier("tt23476204")
```

Thanks for reporting!

**Comment by bugwelle** [comment] 2023-06-20 16:29
I will add "search by ID". I thought we already support that, but it isn't the case.

![Screenshot_20230620_182904](https://github.com/Komet/MediaElch/assets/1667306/b104c8c3-58a9-4180-ae47-0e0c1a00ee8b)

**Comment by bugwelle** [comment] 2023-06-20 16:37
Ok, sorry for the confusion. I assumed this was about TV shows. I think the summer heat is too much for me :smile:

**Comment by bugwelle** [comment] 2023-06-20 16:54
So, I found an issue where the release date was not scrape for movie search results. That's fixed via https://github.com/Komet/MediaElch/pull/1588

![Screenshot_20230620_184809](https://github.com/Komet/MediaElch/assets/1667306/7846e1f8-2ae2-4078-9c05-f595fdf849c2)

I can find "Jungle Queen" and can scrape it as well:

![Screenshot_20230620_185310](https://github.com/Komet/MediaElch/assets/1667306/24bd1fde-4970-4241-983b-c4b742d23309)

Which version of MediaElch do you use?

A new snapshot version will be available in about 30min - 1h.

**Comment by nkatsidis** [comment] 2023-06-22 13:56
downloaded [MediaElch_win_Qt6_2.10.1-dev_2023-06-21_00-31](https://mediaelch-downloads.ameyering.de/snapshots/Windows_10_or_later/MediaElch_win_Qt6_2.10.1-dev_2023-06-21_00-31_git-master-61f3cdd6.zip)

same problem...

**Comment by bugwelle** [comment] 2023-06-25 12:44
Ah, ok. So there was confusion on my part. The issue is, that "Jungle Queen" is not listed as a TV show on IMDb. You can check this by using the "[advanced search](https://www.imdb.com/search/title/)" on IMDb. Example: 

- https://www.imdb.com/search/title/?title=Jungle+Queen&title_type=tv_series,tv_episode,tv_special,tv_miniseries

Only if you explicitly search for movies (feature films), "Jungle Queen" appears:

- https://www.imdb.com/search/title/?title=Jungle+Queen&title_type=feature

This does not seem like anything MediaElch can do about. "Jungle  Queen" is not listed as a TV show or anything related to a TV show (episodes, etc.). That's why you won't find it.

MediaElch only finds it if you search for movies (the movies tab, not TV show tab), hence my confusion in the beginning. :smile: 



Regards,
Andre

**Comment by nkatsidis** [comment] 2023-06-25 12:48
nevertheless search was improved :)
tv show or not :)

**Comment by bugwelle** [comment] 2023-06-25 13:03
Indeed. :smile: 

I'm closing this issue then. Thanks for reporting it anyway, because I found a bug and improved our tests. :)

**Closed by bugwelle** 2023-06-25 13:03 UTC
Labels: bug, component: scraper, component: movies
