### ISSUE TITLE
MediaElch main window stuck on bright white, not adjusting to KDE dark theme

### ISSUE THREAD

**Issue by ioogithub** [Komet/MediaElch#1038] opened 2020-10-19 23:51 UTC
**Describe the bug**

**To Reproduce**
1. Open MediaElch.
2. Observe that the left navigation bar, settings window, right click context menu all inherited the dark theme and look really nice.
3. Observe that the main window background and top navigation bar are drawn in a bright white/off white yellowish colour. It has not inherited the dark them as the other parts of the app have. There doesn't appear to be any setting to adjust the colour. 

**Expected behavior**
I would expect that the app would be able to inherit the colors from the dark theme in all parts of the app.

**MediaElch Version:**
 - [X ] 2.6.6 stable, AppImage version downloaded directly from website.

**Operating System:**
 - [X ] Linux (distribution: KDE Neon 5.20 )

**Additional context**
Is the main window background actually hard coded to be this white colour? I am currently using the Arc Dark global theme. I can see that parts of MediaElch inherit the colour scheme perfectly and beautiful. The main window background however is such a contrast to every other app I have that when I open it it strains my eyes, I have to immediately adjust the screen brightness down. Then when I minimize the window I have to adjust the brightness back up for all my other apps/OS.

If Media Elch can inherit the colours properly for the settings, left navigation bar, right click context menus, progress windows and most other places,, can the main window background and top navigation bar also be fixed?

This is close to a perfect app for me and I have been searching for this for a long time however I won't be able to use it if the main window background is hard coded to be such a bright white.

**Comment by bugwelle** [comment] 2020-10-20 07:07
Hi,

thanks for your feedback! MediaElch's main window has hard-coded colors... A while ago I moved all hard-coded styles to this CSS file: https://github.com/Komet/MediaElch/blob/master/src/ui/default.css

I would need to adjust that file. However, I currently do not have the time to do so. :-/
Only the main window uses custom colors and styles. All other windows are default Qt-windows which adapt KDE's color themes.

Dark-theme support for KDE has been added with v2.6.0 ( see https://mediaelch.github.io/mediaelch-blog/posts/mediaelch-v2.6.0/ ) but no further development has been done since then.

If other contributors are reading this: I would gladly review a dark theme CSS file!

Regards,
Andre

**Comment by ticao2** [comment] 2020-10-20 11:46
And I, as a Windows user, remain very envious of Linux users, who have this Dark version of MediaElch.
How long, my God? **:-)**

**Comment by ioogithub** [comment] 2020-10-21 18:51
> A while ago I moved all hard-coded styles to this CSS file: https://github.com/Komet/MediaElch/blob/master/src/ui/default.css

I can't edit and change this file on my local installation can I?

**Comment by bugwelle** [comment] 2020-10-22 06:49
No, at the moment the CSS file is part of the binary. If you like, I can add an option to [`advancedsettings.xml`](https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings) where you can specify a CSS file that MediaElch loads. Then you could modify the CSS file, restart MediaElch and see your changes.

Would that be acceptable to you? :-)

(I'm unsure whether a "reload window" is easy to implement but I could also look at that)

**Comment by ticao2** [comment] 2020-10-22 15:08
Who knows, maybe this will facilitate the implementation of my old wish for an interface more built to be seen in a Media Center, on a TV with 56 ', about 4 or 5 meters away, larger characters and poster ...
https://imgur.com/gallery/hWRV7eM
But it is just a wish. I'm not a programmer.

**Comment by ioogithub** [comment] 2020-10-23 02:39
> No, at the moment the CSS file is part of the binary. If you like, I can add an option to [`advancedsettings.xml`](https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings) where you can specify a CSS file that MediaElch loads. Then you could modify the CSS file, restart MediaElch and see your changes.

That sounds like a good solution.

**Comment by bugwelle** [comment] 2020-10-23 10:14
Will be implemented with https://github.com/Komet/MediaElch/pull/1040

**Comment by bugwelle** [comment] 2020-10-24 12:50
I've tested https://github.com/Komet/MediaElch/pull/1040 and have added screenshots there. :-)

Please note that there are still quite a few places with hard-coded colors. I have to fix them step by step.

**Comment by ioogithub** [comment] 2020-10-25 17:58
Awesome response time! How can I test this?

**Comment by bugwelle** [comment] 2020-10-26 08:46
You have to create an `advancedsettings.xml` file. Copy the contents from https://github.com/Komet/MediaElch/blob/master/docs/advancedsettings.xml into it.

(_Have a look at our documentation about advanced settings: https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings_ )

Un-comment this line:

https://github.com/Komet/MediaElch/blob/831d3076946bcaecf4f07267e170e4bc829beea9/docs/advancedsettings.xml#L43

And add an absolute path to your copy of `default.css` to it (or a relative one where the path is relative to `MediaElch.exe`).
You can find MediaElch's version at:
https://github.com/Komet/MediaElch/blob/master/src/ui/default.css

To test that MediaElch actually uses the CSS file you can also remove all contents from the stylesheet and start MediaElch. It then should look like the screenshot from #1040. After that simply change the color values and see how it looks (you have to restart MediaElch after each change. I haven't implemented a "reload CSS file", yet).

**Comment by Stunkymonkey** [comment] 2022-02-17 13:24
another issue i noticed with a dark theme, that should get fixed.
the tv-show view has an issue:
![Screenshot-2022-02-17_140935](https://user-images.githubusercontent.com/1315818/154488491-b962dfdf-597d-4245-b049-4c601e301a1e.png)
here the series "Sløborn" has been clicked/selected on. It uses a white background-color.
the movie view is not affected. When a movie is selected it has a (dark-)blue background-color:
![Screenshot-2022-02-17_142417](https://user-images.githubusercontent.com/1315818/154490690-cb1d76cd-cd89-4cb4-a212-c4256945c022.png)

Should I open a new issue?

**Comment by bugwelle** [comment] 2022-02-19 16:57
@Stunkymonkey For that please see: #1412

**Comment by bugwelle** [comment] 2022-12-27 20:22
I'm closing this as a duplicate of #761.

I've done a lot of refactoring today and even played a few minutes with changing colors. The most relevant commit of today was https://github.com/Komet/MediaElch/commit/62c53047d3574f9c2a08e5775ab9fa0f88d6a36f which moved inline stylesheets to our `default.css`.  Replacing colors in that file now works better.

I'll be doing a bit more cleanup and refactoring and will try to write a stylesheet for a dark theme (of our main window at least).

Preview:

<img width="1792" alt="Screenshot 2022-12-27 at 21 20 25" src="https://user-images.githubusercontent.com/1667306/209718410-a9029771-443b-4580-ad3f-2598d925146e.png">

I only placed with it for a few minutes. I know the colors don't look good, I just want to point out that there are only a few placed left that are bright white. Those need to be styled, but it's a lot better now compared to a few months ago.

There is also a lot to do:

- icon colors
- contrast
- consistent color scheme (we have 4 different "blue" colors for labels...)

**Closed by bugwelle** 2022-12-27 20:22 UTC
Labels: feature request, ui
