### ISSUE TITLE
Images not saved

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#561] opened 2018-08-25 14:09 UTC
Mediaelch latest windows

I have many movies with previous accepted by kodi images with filenames:

 - `disc.png`
 - `clearart.png`
 - etc

I have defined in medialech in scraper
`<baseFileName>-clearart.png`

but if Medialech finds clearart.png that is saved locally, by pressing save it does not create `<baseFileName>-clearart.png`

with movies that are scraped for the first time this does not happen.
it only happens with previously saved movies where images already exist.

**Comment by bugwelle** [comment] 2018-09-03 19:10
Thanks for reporting this. I'm a bit late to answer but I'll try my best:

If I've understood you correctly, you have different files in a movie folder (movie, poster, clearart, etc).
If you click "Save", MediaElch should rename the poster, etc?

MediaElch does not rename existing files unless told to. We have a feature called "Renamer" which is inteded for exactly that use case. See: https://mediaelch.github.io/mediaelch-doc/renaming.html

Please let me know if this helps. :-)

**Comment by nkatsidis** [comment] 2018-09-03 20:33
No i dont want the existing files to be renamed.
its just that mediaelch does not create lets say
Movie-clearart.png
if clearart.png exists

same for disc etc

although i have set for <basefilename>-clearart.png to be created.

**Comment by nkatsidis** [comment] 2018-09-14 13:39
can you please check?

**Comment by bugwelle** [comment] 2018-09-15 17:03
> can you please check? 

Sorry, forgot about this issue :)

> its just that mediaelch does not create lets say Movie-clearart.png if clearart.png exists same for disc etc

ok. I'm unsure on how we should handle this. I'll come back to you because I found another bug that is related to your issue:

Given following structure:
```
12 years a slave
 |- logo.png
 |- movie.mov
```

 1. Scrape 12 years a slave (The Movie Db)
 2. Save movie
 3. No `movie-logo.png` was created (this is actually expected, at least to my understanding)
 4. Click on the Logo and select another one
 5. Bug: Instead of the selected logo, the placeholder is shown. `logo.png` is not updated as well.

Thank you for reporting this. :)

**Comment by nkatsidis** [comment] 2018-10-05 21:35
Any news on this?

**Comment by bugwelle** [comment] 2018-10-06 09:48
Sorry, no. I don't have much time at the moment for MediaElch. Furthermore I can't seem to reproduce the bug even though I wrote down the steps to reproduce it. :-/

**Comment by nkatsidis** [comment] 2018-11-20 22:02
I see that you are back :)
can i provide any more info about this issue?

**Comment by bugwelle** [comment] 2018-12-12 12:47
I'm sorry that it took me so long to answer. Most of my current contributions are bugfixes or changes related to publishing the next release.

I don't think that this issue will be fixed in the next version. I plan on refactoring a lot of code which will hopefully make it easier to identify the cause of this.

**Comment by nkatsidis** [comment] 2018-12-12 13:06
thank you

**Comment by dirtkael** [comment] 2019-08-15 19:16
Hello,
2 adds on this bug :
1- All movies in the same folder have the same files logo.png, disc.png, clearart.png, there is no naming of those files depending on the movie name.
![image](https://user-images.githubusercontent.com/54153230/63120080-da065a00-bfa1-11e9-877b-6b9520ed104b.png)

2- in the parameters, if you specify that you don't want logo, disc art or clear art ... it does nothing, these files continue be created.
![image](https://user-images.githubusercontent.com/54153230/63120110-ebe7fd00-bfa1-11e9-9366-82b9ac3822d7.png)

I use MediaElch 2.6.0 stable for windows
I hope I'm clear, I'm french and not that fluent in english anymore.

**Comment by dirtkael** [comment] 2019-08-16 12:49
OK, After more tests, you can forget about the first point.

I didn't change the settings abour logo, clear art and disc art.
Those are not set initially like the others. They miss "<baseFileName>-" in it.
That's for the first point.
About the second one ... It still doesn't work like it should.

Thanks for reading :)

**Comment by bugwelle** [comment] 2019-08-27 15:40
Hi there,

sorry for the late answer. I haven't looked into this issue again but will most likely do that next week. I haven't forgotten about this issue :)

**Comment by bugwelle** [comment] 2020-04-08 14:33
HI everyone,

I was not able to reproduce this issue and think that everything works as intended. But I may misunderstand the issues you are experiencing (maybe a language barrier?).

**To summarize:**  
I have a movie with the following files:

```
Sintel (2010)
├── clearart.png
├── disc.png
├── logo.png
├── movie.mov
└── poster.jpg
```

My settings look like this:

![Screenshot_20200408_162309](https://user-images.githubusercontent.com/1667306/78795376-43196280-79b5-11ea-8937-4220451f35b9.png)

Steps I took:

 1. Reload all movies
 2. Click on Movie (which is marked "new")
  -> No poster, disc or clear art is visible. Nothing is shown. MediaElch ignores the existing files because they do not match the patterns (see screenshot).
 3.  Scrape Movie with all details from TMDb
 4. Click "Save All"

The folder now contains the following files:

```
Sintel (2010)
├── clearart.png
├── disc.png
├── logo.png
├── movie-banner.jpg
├── movie-clearart.png
├── movie-disc.png
├── movie-landscape.jpg
├── movie.mov
├── movie.nfo
├── movie-poster.jpg
└── poster.jpg
```

=> All files without the `movie-` prefix were not changed. 

The files are not used at all which contradicts the original issue if I understood you right.

----------

@dirtkael I was not able to reproduce your second point. If I do not select any scraper for logos, discart, etc. in the custom movie scraper, none are downloaded or saved to disk. :-/

**Comment by bugwelle** [comment] 2023-06-27 15:23
The last point here was:

> I was not able to reproduce this issue and think that everything works as intended. But I may misunderstand the issues you are experiencing (maybe a language barrier?).

I'm therefore closing this issue. Feel free to reply and I will reopen this issue.

**Closed by bugwelle** 2023-06-27 15:23 UTC
Labels: bug
