### ISSUE TITLE
Fixed spacing between icons

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#793] opened 2019-09-19 00:02 UTC
**Describe the bug**
See thescreenshot.
Installed 2.6.2 stable and all of a sudden there's a gigantic spacing between the icons for the different artworks and if I don't make the column wide enough so they all show three dots cover the episode counter under the episode name. And to make it wide enough the column covers like half the screen.

**To Reproduce**
It's there in plain sight so nothing needed for reproducing it.

**Expected behavior**
There shouldn't be a fixed spacing between the icons so they can be showed together without covering the episode counter.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/28609335/65196975-b42d1300-da81-11e9-9842-fd5ad56d9347.jpg)
![Capture2](https://user-images.githubusercontent.com/28609335/65197070-ed658300-da81-11e9-8e69-d013709e5478.jpg)

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [X] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**

**Comment by ticao2** [comment] 2019-09-20 15:58
In Movies, apparently, in version 2.6.2 and 2.6.1, the space between icons was 3 times larger than in version 2.6.0.

**Comment by bugwelle** [comment] 2019-09-29 09:30
I encountered this issue on different platforms as well. It's a strange issue because I don't have this kind of problem on macOS. I currently don't know whether this is an issue caused by a new Qt version or a change on my side. 

Thank you for opening this issue. :-)

**Comment by bugwelle** [comment] 2019-10-20 15:31
Just did some debugging (tested commits that didn't even arrange the icons this way). It's due to a Qt update. I'll look into how we can fix this.

**Comment by bugwelle** [comment] 2019-10-24 17:10
As far as I can tell, it's because icons are drawn next to the cells content... which is empty. We draw icons by using `DecorationRole` instead of `DisplayRole`. We may fix this by implementing a custom Delegate class to draw these icons.

**Comment by bugwelle** [comment] 2020-03-28 15:46
I know that this bug is still open. I wasn't able to fix this issue, yet and it's driving me crazy. 😄 
I don't think this will be fixed in v2.6.6, but maybe in a later version.

**Comment by psonnosp** [comment] 2020-03-28 15:53
I've moved on to 16:9 screens now so it's no longer a problem. Not for me atleast so no worries, but I get the feeling 😉

**Comment by bugwelle** [comment] 2021-03-31 16:39
I FINALLY found the issue... Such a stupid one. I set the column width to 22px but the _minimum_ column width (the default) was 41px. It must have changed in some Qt version.

Will be fixed by  #1266

**Closed** 2021-03-31 16:46 UTC
Labels: bug, dist: Windows, ui

**Comment by psonnosp** [comment] 2021-03-31 21:09
Congrats! Better late than never 😉

**Comment by bugwelle** [comment] 2021-04-01 08:01
Thanks. So annoying, the documentation didn't even list the default value...
https://doc.qt.io/qt-5/qheaderview.html#minimumSectionSize-prop

I'll publish a new Nightly shortly.
