### ISSUE TITLE
Crash while loding Film-Content 

### ISSUE THREAD

**Issue by Arinouko** [Komet/MediaElch#1050] opened 2020-11-16 11:14 UTC
**MediaElch Version:**
2.6.6 stable

**Operating System:**
Linux (Manjaro, installed thru package manager)

**Description:**
After right click on a Film "Informationen laden" (load information) the Pop-Up windows shows the results. After selecting a film the windows closes and MediaElch crashes.

**Terminal Dump:**
```
MediaElch
MediaElch 2020-11-16 12:08:43.617 DEBUG : Loading advanced settings from: FilePath("/home/torsten/.local/share/kvibes/MediaElch/advancedsettings.xml")
MediaElch 2020-11-16 12:08:43.617 WARN  : [AdvancedSettings] advancedsettings.xml not found at  "/home/torsten/.local/share/kvibes/MediaElch/advancedsettings.xml"
MediaElch 2020-11-16 12:08:43.618 DEBUG : Advanced settings:
    locale:                  German
    debugLog:                false
    logFile:                 
    forceCache:              false
    sortTokens:              Der, Die, Das, The, Le, La, Les, Un, Une, Des
    movieFilters:            *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, index.bdmv, *.wtv
    concertFilters:          *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, index.bdmv, *.wtv
    tvShowFilters:           *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, index.bdmv, *.wtv
    subtitleFilters:         *.idx, *.sub, *.srr, *.srt, *.ass, *.ttml
    genreMappings:           
    audioCodecMappings:      
        mpa1l2: mp2
        mpa1l3: mp3
        aac lc: aac
    videoCodecMappings:      
        v_mpeg4/iso/avc: h264
        avc: h264
    certificationMappings:   
    studioMappings:          
    countryMappings:         
    writeThumbUrlsToNfo:     true
    episodeThumb dimensions: 
        width:               400
        height:              300
    bookletCut:              2
    useFirstStudioOnly:      false
    exclude patterns:        

MediaElch 2020-11-16 12:08:43.675 DEBUG : [TMDb] Request setup from server
MediaElch 2020-11-16 12:08:43.687 DEBUG : [TMDb] Request setup from server
MediaElch 2020-11-16 12:08:43.762 DEBUG : [TMDb] Request setup from server
MediaElch 2020-11-16 12:08:43.763 DEBUG : [TMDb] Request setup from server
MediaElch 2020-11-16 12:08:44.110 DEBUG : Entered
MediaElch 2020-11-16 12:08:44.112 DEBUG : Entered
MediaElch 2020-11-16 12:08:44.588 DEBUG : Entered
MediaElch 2020-11-16 12:08:44.589 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:08:44.851 DEBUG : Entered
MediaElch 2020-11-16 12:08:45.461 DEBUG : Entered
MediaElch 2020-11-16 12:08:45.565 DEBUG : Entered
MediaElch 2020-11-16 12:08:45.566 DEBUG : Entered
MediaElch 2020-11-16 12:08:45.989 INFO  : [DownloadsWidget] Start scanning for imports/downloads. Start Timer.
MediaElch 2020-11-16 12:08:46.516 DEBUG : MediaElch version "2.6.6" starting up
MediaElch 2020-11-16 12:08:46.961 DEBUG : Entered
MediaElch 2020-11-16 12:08:47.182 INFO  : Searching for updates
MediaElch 2020-11-16 12:08:48.052 INFO  : [DownloadsWidget] Scanning for imports/downloads took: 2063 ms
MediaElch 2020-11-16 12:08:48.053 INFO  : [DownloadsWidget] Updating imports/downloads lists: 0 ms
MediaElch 2020-11-16 12:08:48.094 DEBUG : [MovieFileSearcher] Adding movie directory "/run/user/1000/gvfs/smb-share:server=192.168.211.2,share=video/S P I E L F I L M E/Einzelordner"
MediaElch 2020-11-16 12:08:48.468 DEBUG : [TMDb] Base url: "http://image.tmdb.org/t/p/"
MediaElch 2020-11-16 12:08:48.470 DEBUG : TMDb base url: "http://image.tmdb.org/t/p/"
MediaElch 2020-11-16 12:08:48.471 DEBUG : [TMDb] Base url: "http://image.tmdb.org/t/p/"
MediaElch 2020-11-16 12:08:48.471 DEBUG : [TMDb] Base url: "http://image.tmdb.org/t/p/"
MediaElch 2020-11-16 12:08:48.471 DEBUG : [TMDb] Base url: "http://image.tmdb.org/t/p/"
MediaElch 2020-11-16 12:08:48.506 DEBUG : Now processing files
MediaElch 2020-11-16 12:08:49.670 INFO  : [TvShowFileSearcher] Reload TV shows, clear database: false
MediaElch 2020-11-16 12:08:49.689 DEBUG : [TvShowFileSearcher] Searching for TV shows done
MediaElch 2020-11-16 12:08:49.689 INFO  : [DownloadsWidget] Start scanning for imports/downloads. Start Timer.
MediaElch 2020-11-16 12:08:49.690 DEBUG : [TvShowFilesWidget] Renewing model | Forced: true
MediaElch 2020-11-16 12:08:49.690 INFO  : [DownloadsWidget] Scanning for imports/downloads took: 0 ms
MediaElch 2020-11-16 12:08:49.690 INFO  : [DownloadsWidget] Updating imports/downloads lists: 0 ms
MediaElch 2020-11-16 12:08:49.723 DEBUG : Searching for concerts done
MediaElch 2020-11-16 12:08:51.760 DEBUG : Entered, movie= "(T)Raumschiff Surprise - Periode 1 (2004)"
MediaElch 2020-11-16 12:08:52.085 DEBUG : Entered
MediaElch 2020-11-16 12:08:52.115 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:08:52.132 DEBUG : Entered
MediaElch 2020-11-16 12:08:52.133 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:08:52.133 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:08:52.133 DEBUG : Entered
MediaElch 2020-11-16 12:08:52.133 DEBUG : "(T)Raumschiff Surprise - Periode 1 (2004)"
MediaElch 2020-11-16 12:08:52.133 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:08:52.133 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:08:55.442 DEBUG : Entered, currentIndex= 0
MediaElch 2020-11-16 12:08:55.442 DEBUG : Entered
MediaElch 2020-11-16 12:08:55.442 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:08:55.442 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:08:55.443 DEBUG : [MovieSearch] Open window
MediaElch 2020-11-16 12:08:55.443 DEBUG : Entered, searchStr= "(T)Raumschiff Surprise - Periode 1 (2004)"
MediaElch 2020-11-16 12:08:55.609 DEBUG : [Search Results] Count:  1
MediaElch 2020-11-16 12:08:55.610 DEBUG : [Search Results] Count:  1
MediaElch 2020-11-16 12:09:25.180 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:09:25.181 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:10:07.458 DEBUG : Entered, currentIndex= 0
MediaElch 2020-11-16 12:10:07.459 DEBUG : Entered
MediaElch 2020-11-16 12:10:07.459 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:10:07.459 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:10:07.459 DEBUG : [MovieSearch] Open window
MediaElch 2020-11-16 12:10:07.459 DEBUG : Entered, searchStr= "(T)Raumschiff Surprise - Periode 1 (2004)"
MediaElch 2020-11-16 12:10:07.519 DEBUG : [Search Results] Count:  1
MediaElch 2020-11-16 12:10:07.520 DEBUG : [Search Results] Count:  1
MediaElch 2020-11-16 12:10:08.853 DEBUG : Entered
MediaElch 2020-11-16 12:10:08.854 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:10:08.854 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:10:08.854 DEBUG : Entered, message= "Lade..." id= 20005
MediaElch 2020-11-16 12:10:08.920 DEBUG : Entered
MediaElch 2020-11-16 12:10:08.963 DEBUG : Entered
MediaElch 2020-11-16 12:10:09.130 DEBUG : Entered
MediaElch 2020-11-16 12:10:09.226 DEBUG : Entered
MediaElch 2020-11-16 12:10:09.321 DEBUG : Entered
MediaElch 2020-11-16 12:10:09.328 DEBUG : Entered
MediaElch 2020-11-16 12:10:09.399 DEBUG : Entered, enabled= true
MediaElch 2020-11-16 12:10:09.409 DEBUG : Entered, enabled= false
MediaElch 2020-11-16 12:10:09.409 DEBUG : [FanartTv] Load movie data with image types: QUrl("https://webservice.fanart.tv/v3/movies/9805?api_key=842f7a5d1cc7396f142b8dd47c4ba42b")
MediaElch 2020-11-16 12:10:09.789 DEBUG : [NotificationBox] Hide Progress bar with id 20005
MediaElch 2020-11-16 12:10:09.791 DEBUG : Entered, id= 20005
MediaElch 2020-11-16 12:10:09.791 DEBUG : Entered, msg= "Lade Bilder..." id= 20005
MediaElch 2020-11-16 12:10:09.791 DEBUG : Entered, message= "Lade Bilder..." id= 20005
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/93PW1NGTkcYxgCfPfd0m4xa7rHJ.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Start next download
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/18DKtAo9KTvRFqCe5VV8o3hJJWg.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/adVIg5zyp42gEej6KmpqiTgC7Bn.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/RGhJFP6AbtgmXCbykmRykIQXaw.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/oBoY5DNa2DmAxixjmJFXgjA2z7A.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/qUXzjY4LllmhMadbdOhzvFtllhR.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/10VtnxsW6h8hsKYmPc2qimiBQiz.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/x9N5fOwwWZppbbr6XqBiDkDBFme.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/iCpfVjPn9fMCm9RSgHAlBIo1zUu.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/vtgedBDox7Qmh8v10JsF6nEy0i1.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/yVEvRjx3iKU4dMiPiHp2BtVFmUF.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/6MRDSbBG3xn6wQYDOGNvNFZfkkh.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/8XhgDkbhJ9WfuFsatSdP2rt5OZb.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/u6oi2kposIQPSAbHY7nuYMHxr4Y.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/oBh8co3odGzjUcwQkqsVQZensOl.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/4pLUxKxFXQC6JjIqKv6UujRbloV.jpg")
MediaElch 2020-11-16 12:10:09.794 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/lbJxpVVhF3OeZS0ldDhcgIgnFZB.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/9CIngBaUFjdkn1JfMAavMyOno9X.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/el1BQD34maVxVwGxrWyUh49GRVn.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/29bDZh82jq5Ue6QM1swV1OHNVXY.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/mgn9YoLNf78AsGBYgXunDCR4Cgr.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/os3qZAfBcyR076BjX8lTMgBISFs.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/7EBm3MZjzEGz7QpJBrWML7tV5yq.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/rBCpkhZSD97hA1b2S6mWIwSBrYV.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/qCdQ74WI765kLOJBWKJ1qVamU42.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/9805/hdmovielogo/traumschiff-surprise---periode-1-5092a46a197cd.png")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/9805/hdmovieclearart/traumschiff-surprise---periode-1-5092a47daf3af.png")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/9805/moviedisc/traumschiff-surprise---periode-1-5012beac6458a.png")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/9805/moviebanner/traumschiff-surprise---periode-1-51a8da85761ec.jpg")
MediaElch 2020-11-16 12:10:09.795 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/9805/moviethumb/traumschiff-surprise---periode-1-51a8da966ce34.jpg")
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by bugwelle** [comment] 2020-11-16 11:32
_Offtopic in German: Traumschiff Surprise ist ein verdammt geiler Film, gute Wahl! 😄_

I guess that we still have a race condition in our download manager...

**Comment by Arinouko** [comment] 2020-11-16 13:28
> _Offtopic in German: Traumschiff Surprise ist ein verdammt geiler Film, gute Wahl! smile_
 Ja, aber :-) er crasht leider auch bei schlechten Filmen...

**Comment by kdrobnyh** [comment] 2020-11-27 13:51
Have the same problem. Can it be avoided by change in settings? Say, limiting to one file download at a time?

**Comment by kgarlicki** [comment] 2020-12-04 19:37
+1 Currently nothing can be done with the application since it is crashing right after the scraping.

**Comment by bugwelle** [comment] 2020-12-12 16:28
Hi,

I just wanted to inform you that I was able to reproduce this issue on Manjaro XFCE and that the bug will be fixed by #1078.
Turns out that this bug only happened with Kvantum installed which is why I wasn't able to reproduce this bug (I used Manjaro KDE for testing before...).

Regards,
Andre

**Closed** 2020-12-12 16:31 UTC
Labels: bug

**Comment by bugwelle** [comment] 2020-12-12 16:32
#1078  is now merged. If you compile MediaElch yourself, check out the latest master. If not you will have to wait for the next release.

If this issue wasn't fixed for you, please let me know.

**Comment by kdrobnyh** [comment] 2020-12-13 00:33
Just built the latest master and the problem is still there. Loading information from IMDb works fine, but crashes almost every time I load information from The Movie DB.

**Comment by bugwelle** [comment] 2020-12-13 13:30
Thank you for confirming! :-)
