### ISSUE TITLE
Doesn't open in Big Sur mac OS

### ISSUE THREAD

**Issue by clamel71** [Komet/MediaElch#1059] opened 2020-11-24 22:42 UTC
**Describe the bug**

**To Reproduce**
4. See error / Crash

**Expected behavior**

**Screenshots**

**MediaElch Version:**
 - [ ] 2.6.7-dev (nightly)
 - [ ] 2.6.6 stable

**Operating System:**
 - [ ] Windows
 - [x] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by bugwelle** [comment] 2020-11-25 08:02
Hi,

this is a known issue and a duplicate of https://github.com/Komet/MediaElch/issues/1035 :-)

I've provided a binary that works on macOS Big Sur on the Downloads page here:
https://mediaelch.github.io/mediaelch-doc/download.html (see the warning box)

**Closed by bugwelle** 2020-11-25 08:02 UTC
