### ISSUE TITLE
[TvShow] Crash if "Show all episodes" is enabled

### ISSUE THREAD

**Issue by dfarin** [Komet/MediaElch#669] opened 2019-02-17 22:20 UTC
Hiho, i loaded 2.60 and start like usual. ME needs starts scanning dirs and most times directly crashes after scan, and sometimes i can click a tv show but then it crashes immediately after i choose "show missing episodes"
Sorry for my bad English ;)
What data do u need to help u finding the bug ?

System: Windows 10

**Comment by bugwelle** [comment] 2019-02-18 06:10
Hi, thanks for the report. I'll try to reproduce this and will come back to you if I need more information.
Don't worry about your English. It's fine as long as we can understand each other :-)

May be related to #641

**Comment by bugwelle** [comment] 2019-02-19 08:51
Wow. Can reproduce this. It only happens if "Show missing episodes" is enabled. I'm not even able to start MediaElch. Definitely a serious bug. Thanks for reporting!

**Comment by bugwelle** [comment] 2019-02-19 09:11
Also happens on Linux.

**Comment by bugwelle** [comment] 2019-02-21 16:31
I *think* this will be fixed in #674. Why "think"?
Because I don't really understand what happened. I fixed a few issues but can't say *for sure* which bug causes/caused this. You may need to delete `MediaElch.sqlite` (see https://mediaelch.github.io/mediaelch-doc/faq.html#where-are-mediaelchs-settings-stored => temporary file directory).

**Comment by bugwelle** [comment] 2019-02-21 17:23
This bug has been around since even before version 2.4.2. This reason that it popped up just now is that I changed some internal structure changes. It was pure luck (I guess) that MediaElch didn't crash before. :-)

**Closed** 2019-02-21 17:41 UTC
Labels: Linux, Windows, bug, high priority
