### ISSUE TITLE
Trying to Scrape a Show Crashes Mediaelch

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#741] opened 2019-07-10 21:19 UTC
Latest Nightly, Windows 10 64 bit

Trying to Scrape a Show Crashes Mediaelch (that simple) :)

**Comment by bugwelle** [comment] 2019-07-11 06:33
Duplicate of https://github.com/Komet/MediaElch/issues/716

I'm sorry to hear that MediaElch crashes. I'll look at it on the weekend :)

**Closed by bugwelle** 2019-07-11 06:33 UTC
