### ISSUE TITLE
[Navbar] Menu icon design

### ISSUE THREAD

**Issue by captainfluorescent** [Komet/MediaElch#1329] opened 2021-05-14 07:51 UTC
I noticed in the latest update of MediaElch for Mac -Catalina- (2.8.12 Coridian), that the icons on the menu are different and less intuitive; the graphic is very thin and I cannot understand the reason of this change.
Can it be reverted to previous icons set?

**Comment by bugwelle** [comment] 2021-05-14 11:51
The reason for this change is that we now use SVG vector images. We use vector images as they make usage on High DPI display possible.

Also, the origin of those icons is unclear (neither I nor the @ Komet can find them on the internet anymore) and the new ones have a better license (LGPL3).

I can understand that the icons are too thin for you. I'll see how we can improve that.

Please let me know what icon(s) you find especially un-intuitive.

**Comment by captainfluorescent** [comment] 2021-05-14 12:03
hello Andre, and sorry for my impulse to write here -first time ever-
Answering your question, I find the Sync, Reload/Refresh and  the Settings icons are the more problematic to understand (a part of their thin outline).
But I am sure, in the future, will be possible to find some royality free ones, in case you decide to make the change. 
In any case, thank you for your reply and the good job with this useful app!

**Comment by bugwelle** [comment] 2021-05-14 12:22
Hi,

there are plenty of open-source icons themes. The issue is more that nearly none provide all icons that I'd like to have (on top of missing vector graphics).

I've decided to use KDE Breeze (see https://cdn.kde.org/breeze-icons/icons.html ) because it's the default icon theme for KDE (the desktop environment a lot of Linux distributions use). :-)
They provide a standardized icon set. Personally, I prefer a gear icon to the current settings icon as well, but it's their standard icon for settings and that's why I used it.

Furthermore, I plan on using more icons from them (to use in buttons, etc.). To have a consistent look&feel, I decided on KDE Breeze icons.

The icons are indeed quite thin. I'll switch them with smaller ones that I scale up (KDE provides different size-variants with different border sizes). That should do the trick.

I'm thankful for your honesty and your feedback. I won't change the settings icon. The reload and sync icons could be improved, indeed. Maybe I'll use `view-refresh` for the reload button (see link above).

Regards,
Andre

**Comment by bugwelle** [comment] 2022-12-17 22:11
I'm closing this issue. With the upcoming Qt6 releases (already available as Nightlies), the icons are better visible on HighDPI displays as well. I think they're fine as is. If someone finds better icons, I welcome them do propose them. I'm open to new ideas. :)

**Closed by bugwelle** 2022-12-17 22:11 UTC
Labels: feature request, ui
