### ISSUE TITLE
Can't get media info from files

### ISSUE THREAD

**Issue by Loki3000** [Komet/MediaElch#555] opened 2018-08-20 20:46 UTC
Last versions of MediaElch can't get media info from files. Old version (I don't remember version number) has got data and store it in database:
![default](https://user-images.githubusercontent.com/12333165/44365126-86b61480-a4d1-11e8-89de-f258242aae3e.png)
But if I try to get media info from file at current version, all fields becomes empty:
![default](https://user-images.githubusercontent.com/12333165/44365189-c1b84800-a4d1-11e8-9831-b5563218b699.png)
Old version was installed from deb repository. Now i'm using *.AppImage file if it matters.

MediaElch 2.4.3-dev - Talax

Compiled with Qt version 5.10.1 (64 Release, GCC 7.3.0)
Using Qt version 5.10.1
System: Linux Mint 19 (x86_64-little_endian-lp64)

**Comment by alexls74** [comment] 2018-08-20 21:55
Have you installed MediaInfo?

**Comment by bugwelle** [comment] 2018-08-21 06:03
That's a problem with the AppImage version as far as I know.
Could you try to install libmediainfo as mentioned by @alexls74 ? :-)

**Comment by alexls74** [comment] 2018-08-21 06:25
btw
Let me know if you find any bugs in Russian translation ;)

**Comment by bugwelle** [comment] 2018-08-21 16:54
@Loki3000 A new debian/ubuntu repository will be added when the next stable version is released. This will still take a while. The AppImage was released as a nightly version for testing.

I tried to fix this for quite a while but with no success :/

> If I found something terrible, I could even join to project in transifex:)

This would be great! But the sources on transifex for MediaElch are not up to date. I'll write Komet and ask for permissions to update the sources on transifex myself. :)

**Comment by alexls74** [comment] 2018-08-21 22:25
> Anyway, I already install libmediainfo0v5 and even mediainfo (console app). Still with no luck.

That's strange.
Could you replace /usr/bin/MediaElch with this [one](https://dropmefiles.com/VexAB) and provide the [log](https://github.com/Komet/MediaElch/blob/master/doc/advancedsettings.xml)?

**Comment by alexls74** [comment] 2018-08-23 04:05
Got It.

libmediainfo has conflict with AppImage's libraries

@bugwelle Could you update the deployment script to include compatible versions of libmediainfo and libzen?

**Comment by bugwelle** [comment] 2018-09-03 19:13
Interesting. Thanks for looking into this, @alexls74 
I won't have time to fix and test this issue until two weeks from now. Can't say if it will take 5min or 5h to fix this. :-)

**Comment by XtradrY** [comment] 2018-09-05 05:17
From what I've seen in the linux appimage on Ubuntu 18.04 the issue is with the ffmpeg that comes bundled with the appimage.
Some libraries required by it are not part of the appimage and are linked to the libraries of the hosts main OS. I was able to satisfy a few dependencies, but some libraries are not available for the Ubuntu 18.04 repositories.

**Comment by bugwelle** [comment] 2018-09-11 15:52
Ok. I'll remove `ffmpeg` altogether in the appimage. I think a new setting option "ffmpeg path" would be a good idea.

**Comment by bugwelle** [comment] 2018-09-23 09:48
Ok, so #594 will hopefully fix this. I've added  `libmediainfo.so.0` to the AppImage. I thought that I had already tried it but I may have forgotten the `.0`. media-info loads the library at runtime so linuxdeployqt wasn't able to automatically include it in the AppImage. :)

**Closed** 2018-09-23 10:50 UTC
Labels: bug
