### ISSUE TITLE
2.6.4 Crashing on Import

### ISSUE THREAD

**Issue by Arszozah** [Komet/MediaElch#925] opened 2020-03-15 21:18 UTC
**Describe the bug**
The program crashes on import. 

**To Reproduce**
Go to import, successfully scrape movie details, hit import and program closes

**Expected behaviour**
I expect the movie to be imported to the correct folder.

**MediaElch Version:**

 - [ ] 2.6.4 stable

**Operating System:**
 - [ ] Windows

**Comment by bugwelle** [comment] 2020-03-16 08:24
Duplicate of https://github.com/Komet/MediaElch/issues/828

Thank you for confirming this issue.

**Closed by bugwelle** 2020-03-16 08:24 UTC
