### ISSUE TITLE
Crash when reloading Concerts

### ISSUE THREAD

**Issue by dorseg** [Komet/MediaElch#1335] opened 2021-05-19 20:55 UTC
**Describe the bug**
When clicking on "reload all concerts", the app crashes. Usually happens if already loaded concerts have been deleted/moved to other destination. Didn't happen before version 2.8.8.

**To Reproduce**
1. Go to 'Concert'.
2. Click on 'Reload all Concerts'.
3. Wait for concerts to be loaded.
4. Delete or move the loaded concerts to other destination.
5. Click again on 'Reload all Concerts'.
4. The app crashes after 'ConcertFileSearcher' with the error 'Index is invalid'.

Logs -

**MediaElch 2021-05-03 19:07:43.092 DEBUG : [ConcertFileSearcher] Adding concert directory "/concerts"
MediaElch 2021-05-03 19:07:43.094 DEBUG : Index is invalid**
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
03/05/2021 19:07:43 deleted 50 tile_row polling images.
03/05/2021 19:07:43 Restored X server key autorepeat to: 1
[services.d] stopping openbox...
[services.d] stopping statusmonitor...
[services.d] stopping logmonitor...
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Expected behavior**
The app should not crash.

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [x] 2.8.12 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux - docker container based on ubuntu-18.04 (https://hub.docker.com/r/masonxx/mediaelch)

**Comment by bugwelle** [comment] 2021-05-20 07:21
Hi,


thank you for reporting this issue.  The debug message "Index is invalid" is harmless, it only means that the current selection isn't valid (which is to no surprise if there aren't any concerts) :-)

The "Reload all concerts" functionality wasn't changed in v2.8.8 as far as I remember...

But the one for movies contained a few bugs.

I will have to try it with the docker image as I can't reproduce it as of now. 


Regards,

Andre

**Comment by bugwelle** [comment] 2021-05-20 07:54
Do you have the `Dockerfile` for your docker image so that I can build it locally myself? :)

**Comment by dorseg** [comment] 2021-05-20 08:00
https://github.com/mason-xx/docker-mediaelch/blob/master/Dockerfile

**Comment by bugwelle** [comment] 2021-06-11 17:00
Sorry, I currently don't have the time to look into this. But I haven't forgotten about your issue :)

**Comment by bugwelle** [comment] 2022-01-22 15:29
Hi,

I finally found time to try to debug this issue.

While the log you provided tells me where the app probably crashed, I see nothing that would indicate to me why it would.
I started your docker image successfully and followed all steps that you mentioned. Add concerts, reload, remove one/all concerts or even the parent directory and reload again. MediaElch did not crash.

A few more questions that may help find the bug:

- How many concert directories are listed in the settings?
- Is this reproducible?
- What host system do you use?
- What filesystem does your host use?

Regards,
Andre

**Comment by dorseg** [comment] 2022-01-23 08:27
Hi @bugwelle ,

Thanks for addressing the issue.
- How many concert directories are listed in the settings?
Attaching a screenshots of the settings -
![image](https://user-images.githubusercontent.com/23405857/150670464-7710f04a-8c8e-4247-8460-b592383b29a3.png)
- Is this reproducible?
Yes, I can still repdocuce the issue as mentioned above
- What host system do you use?
Unraid 6.9.2
- What filesystem does your host use?
xfs

**Comment by bugwelle** [comment] 2022-01-23 16:07
Reproduced the issue.

Steps as mentioned by you, but one important detail: You need a concert that has images loaded, movie details alone are not enough. Turned out I had refreshed my test library (cleaned it) and had no images.

Thank you very much for reporting it and being so patient. I will look into this bug ASAP.

**Comment by bugwelle** [comment] 2022-01-23 16:44
I fixed the bug in #1403. Again, thank you very much for reporting this issue!

**Comment by dorseg** [comment] 2022-01-23 16:50
@bugwelle Thank you for the fix 😊

**Comment by bugwelle** [comment] 2022-01-23 16:57
Fix is in `master` branch. :-)

**Closed** 2022-01-23 16:56 UTC
Labels: bug, component: concerts

**Comment by dorseg** [comment] 2022-01-24 11:05
@bugwelle When is it expected to be released?

**Comment by bugwelle** [comment] 2022-01-25 12:31
I don't have a release plan, yet. I make releases on weekends but I won't have time for that  until mid-February. I'd say a new release can be expected by 20th of February. Maybe sooner, depending on whether I find time. :-)
