### ISSUE TITLE
Ver MediaElch_2.6.2_win Not Sorting New TVShows Or TVShows With New Episodes

### ISSUE THREAD

**Issue by lynxstrike** [Komet/MediaElch#789] opened 2019-09-15 13:40 UTC
**Describe the bug**
MediaElch_2.6.2_win [STABLE] not displaying first new tv shows or, tv shows with new episodes.
They are only "Starred" and displayed in its place (not at the first positions as in ver. 2.4.2).
Then, when you click on them, they are re-position now at the firs place on the listing

**To Reproduce**
1. Add a new tv show or new episodes to a tv show already in MediaElch
2. Click on 'Reload Al TV Shows'
3. Scroll down to 'the name of the new tv show, or the show you added new episodes'
4. Click on it (it should re position to its proper place at the beginning of the tv shows listing 

**Expected behavior**
New tv shows or tv shows containing new episodes should be listed first in the listing.

**Screenshots**

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [X] 2.6.2 stable

**Operating System:**
 - [X] Windows    10 Pro x64, 1903 build 18362.356
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**

**Comment by bugwelle** [comment] 2019-09-15 16:52
Hi @lynxstrike 

Thank you for reporting this issue. It's most likely a bug. I had issues with the list/table widget in the past and some of my changes may have introduced this bugs.

I'll look into this after my vacation (i.e. next month). This will be fixed in the next stable version v2.6.4 (planned for November).

PS: I modified your issue.  If you remove the spaces of in the checkbox they will appear as such. (`[x]`) :-)

**Comment by spooki3** [comment] 2019-11-19 20:12
I have the same issue on macOS so at least it appears not to be OS related

**Comment by lynxstrike** [comment] 2019-12-10 14:11
Just a quick update:
As of build:      MediaElch_win_2.6.3-dev_2019-11-27_17-28_git-master-5f93809
MediaElch is sorting first all NEW tvshows (not previously scrapped)   :)  yey!  :)   ... but OLD tvshows (already identified) are NOT sorted  :(  awww   :(

Hope this help with this issue...    Happy holidays everyone!

**Comment by bugwelle** [comment] 2019-12-13 08:26
Hi,

sorry about this but I was (yet again) not able to fix this issue. It's in the back of my head, so I won't forget about this. :)

**Comment by slashy** [comment] 2020-01-14 06:54
Any news on when this will hit stable or should I just use one of the nightly builds?

**Comment by bugwelle** [comment] 2020-01-18 16:52
Next stable version will take me another month. Due to exams at my university, I don't have that much time at the moment to invest into MediaElch. :-/

**Comment by bugwelle** [comment] 2020-02-04 13:54
This is the last and most important issue before I release a new version. I'll use this issue to write my thoughts, ideas and possible fixes for this issue. They are development-focused and won't be helpful to you. It's just so that I don't forget this and it may be helpful in the future if a similar issue arises.

### Problem / Issue
The issue is with the TvShow model, i.e. the model that is responsible for displaying all TV shows in a tree-like widget. When MediaElch reads the list of shows it manages, each show is appended to the model one at a time. The Qt [View/Model](https://doc.qt.io/qt-5/model-view-programming.html) for the TreeView requires us to call `beginInsertRows` before adding a row. This is required for the TreeView to know that a change occurs and that the underlying data is about to change. We do this for TV shows. But when we add further seasons or even single episodes, we skip the model and change the underlying data. The model does not notice that rows have been added and might crash. But when does MediaElch add seasons to shows? That happens when the feature "Show missing episodes" is enabled. And that was exactly the first bug in regards to this that was found. MediaElch crashed if missing episodes should be loaded.

### Possible Solution
We either need the underlying data (i.e. `SeasonModelItem`,...) to have a link to the model and call `beginInsertRows` or (my preferred way) to let all data changes go through the model (`TvShowModel`).

**Comment by bugwelle** [comment] 2020-02-04 14:21
#883 is a work in progress PR that will fix this issue.

**Comment by bugwelle** [comment] 2020-02-04 20:06
Hi there,

I'm now quite sure that #883 will fix this issue and won't make #735 appear again.
If it does (or anything crashes or happens unexpectedly) please let me know immediately.

**Closed** 2020-02-04 20:26 UTC
Labels: bug
