### ISSUE TITLE
Streamdetails do not display Audio Channels when Reload From File

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1174] opened 2021-01-11 09:11 UTC
latest 2.8.4 9/1/20 Windows version

Go to a Movie -> Stream Details -> Reload from File

No audio channel info is displayed

**Comment by bugwelle** [comment] 2021-01-11 09:41
Duplicate of #1172

Will look into it at the end of this week :-)

Thanks for reporting!

**Closed by bugwelle** 2021-01-11 09:41 UTC
Labels: duplicate

**Comment by bugwelle** [comment] 2021-01-14 18:05
Fixed by #1178
