### ISSUE TITLE
Number of channels stays empty with latest versions (2.8.4 and development pull from git)

### ISSUE THREAD

**Issue by count00zero** [Komet/MediaElch#1172] opened 2021-01-09 19:03 UTC
When fetching the Stream-Details from File, the number of channels stays empty => I have to insert the number of channels manually, otherwise my renaming template won't include the number of channels.

**Expected behavior**
Number of Audio-Channels should be gathered, shown and saved.

**MediaElch Version:**
2.8.5-dev (nightly)
2.8.4 stable

**Operating System:**
Windows & Linux (Ubuntu 20.10)

![grafik](https://user-images.githubusercontent.com/14225157/104106389-b7bb5d80-52b5-11eb-97cd-5c700a043e47.png)

**Comment by bugwelle** [comment] 2021-01-11 10:06
Thanks for reporting! Will look into it at the of the week. May be due to a MediaInfoLib update... :-/

**Comment by ticao2** [comment] 2021-01-11 19:19
My test

**Channels Audio**
2.8.3 2020-12-20 = OK
2.8.3 2021-01-02 = OK
2.8.3 2021-01-06 = ERROR
2.8.4 2021-01-09 = ERROR

**Comment by bugwelle** [comment] 2021-01-14 17:49
@ticao2 Thank you! That helped to find the bug in 5min. Fix is on the way.

**Comment by bugwelle** [comment] 2021-01-14 18:06
Fixed by #1178

**Closed by bugwelle** 2021-01-14 18:06 UTC
Labels: bug

**Comment by count00zero** [comment] 2021-01-14 18:17
great job !!

**Comment by bugwelle** [comment] 2021-01-14 18:50
Sorry for this regression. Should not have happened in the first place. :-)

**Comment by ticao2** [comment] 2021-01-15 22:57
@bugwelle   For your information:
I usually have 7 or 8 ME in operation. At least 6 ME. 
All in Portable mode. In various versions dev.
1 or 2 for the total collection of ready-made Movies.
1 for Documentaries.
1 for Series.
1 for Concerts.
1 for Movies that are still without subtitles.
1 or 2 for new Movies.
Today I have 10 ME because of the tests I did.
I don't use it for music. But if necessary I can install it for testing with a few discs.
Windows 10 Pro 64.
So it was easier to see in which **dev** the problem started to occur.
So if you need any information or testing, just ask. **:-)**

**Comment by bugwelle** [comment] 2021-01-16 14:35
@ticao2 Thanks! :)
