### ISSUE TITLE
Search bar not scaling right on 4k 200% scaling

### ISSUE THREAD

**Issue by ozorfis** [Komet/MediaElch#1488] opened 2022-11-02 03:44 UTC
**Is your feature request related to a problem? Please describe.**
My screen resolution is 4k with 200% scaling. The search bar does not scale right on my setup so that I have a hard time hitting the window to type something in or read what I have just typed in.

**Describe the solution you'd like**
I would like to have a proper scaled search bar that I can click on and read.

**Describe alternatives you've considered**

**Additional context**
https://postimg.cc/Lh5Kwyrw

**Comment by bugwelle** [comment] 2022-11-06 11:46
Hi, thanks for reporting this issue. Yes, we have huge problems with 4k and non-100% scaling. If I sent you a ZIP file (assuming you are using Windows), could you test a custom build of MediaElch? The UI framework we use has a new major version which my fix scaling issues.

**Comment by bugwelle** [comment] 2022-11-06 11:46
Related / duplicate of https://github.com/Komet/MediaElch/issues/429

**Comment by ozorfis** [comment] 2022-11-06 15:35
Hi,

of course I would gladly test a custom build and yes I am on Windows 10 22h2.

Best regards
Florian

**Comment by bugwelle** [comment] 2022-11-06 18:28
Thanks. I'll ping you in this issue if a test-version is available. I've updated our release-scripts for [macOS](https://github.com/Komet/MediaElch/issues/1490), Windows will come next.

**Comment by bugwelle** [comment] 2022-11-13 14:22
Current state: Build & Packaging script works locally. Screenshot (my system is German, but you can clearly see the differences)

![Screenshot_20221113_151954](https://user-images.githubusercontent.com/1667306/201526691-5dab6ebe-2085-49be-98af-c36f9dad49e1.png)

**Comment by bugwelle** [comment] 2022-11-13 19:16
MediaElch is now packaged with Qt6. Snapshots are available at https://mediaelch-downloads.ameyering.de/snapshots/Windows_10_or_later/

Only Windows 10 or later is supported (untested on Windows 11; I only have Windows 10).

I tested it with 175% scaling on a 4k display. Works as shown in the display.
Please let me know of any issues you find (please open a new GitHub issue then).

Fixed by https://github.com/Komet/MediaElch/pull/1492

**Closed by bugwelle** 2022-11-13 19:16 UTC
Labels: bug, ui, duplicate

**Comment by ozorfis** [comment] 2022-11-13 19:35
Awesome it works and has never looked that good - thank you!

**Comment by bugwelle** [comment] 2022-11-13 19:54
> Awesome it works and has never looked that good - thank you!

Thanks for confirming it! I'll update our documentation next.
