### ISSUE TITLE
MediaElch not import all files

### ISSUE THREAD

**Issue by YoSiJo** [Komet/MediaElch#1029] opened 2020-10-06 12:18 UTC
**Describe the bug**
Single files of a folder are imported and appear under series, others are not.

**To Reproduce**
1. Config a series directory
2. Scan for files
3. Search for your file in the new entrys

**Expected behavior**
I see all the mkv, avi and other video files of the directory.

**MediaElch Version:**
 - [ ] 2.6.7-dev (nightly)
 - [x] 2.6.6 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: ArchLinux)

**Additional context**
I have already activated the debug log, but unfortunately there is no mention of this file.
Also an error that could be related to it, I could not see at first sight, but here I might be wrong.
I have also looked into the SQLite file to see if the file might appear, but unfortunately not.
If it helps, I can give you the mediainfos of the file or others.

**Comment by rassaei** [comment] 2021-11-23 13:51
This seems to be a duplicate of https://github.com/Komet/MediaElch/issues/1028

**Comment by bugwelle** [comment] 2021-11-27 09:41
Thank you for this issue. As it seems to be a duplicate of #1028, I'll close this issue and will reply to your  other issue on more detail. :)

**Closed by bugwelle** 2021-11-27 09:41 UTC
