### ISSUE TITLE
Can't manually add director and writer.

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#933] opened 2020-03-24 05:21 UTC
**Describe the bug**
You can't manually add director and writer for episodes.
What ever you put into the fields are replaced with 'Unknown ...' when you save or click on another episode and then return to the episode you just tried to fix..

**To Reproduce**
1. Go to episode of choice.
2. Add a Director/Writer by clicking the +-button.
3. Select one in the drop down or put in one manually.
4. Save and click on another episode and then back again.
5. The text is now replaced with 'Unknown Director/Writer'.

**Expected behavior**
That the Director/Writer is saved properly.

**MediaElch Version:**
 - [X] 2.6.5-dev (nightly)
 - [x] 2.6.4 stable

**Operating System:**
 - [X] Windows
 - [x] macOS
 - [x] Linux (distribution: ___)

**Comment by bugwelle** [comment] 2020-03-24 06:44
Oh, I have a bad feeling. I think I know the reason. Will look into it ASAP. Hopefully this evening.

**Comment by psonnosp** [comment] 2020-03-24 07:05
No stress what so ever, I just reported it since I found it.
It's probably the the first time ever that I've done this and it and it was just because TheTVDB had a hiccup so the episode wouldn't scrape so it's something that atleast I can live without 😉

**Comment by bugwelle** [comment] 2020-03-27 19:46
Wow, I'm surprised that this wasn't reported before. This issue exists since v2.4.2. Or maybe it was caused by an update of Qt (the GUI framework MediaElch uses). Haven't checked for that. But with v2.4.2 and Qt 5.14 this bug exists as well.

The issue is a different one than I expected. Sorry, still looking into it.

**Comment by bugwelle** [comment] 2020-03-27 20:05
Oh, I can't believe how stupid this issue was. There was simply never a signal/slot connection for the "edit" event which means we never processed the edited fields...

Will be fixed by #936

**Closed** 2020-03-27 20:17 UTC
Labels: bug, component: TV shows

**Comment by psonnosp** [comment] 2020-03-28 15:58
I've been using ME since it was like created and this was the first time I encountered it so not that strange no one have reported it to be honest.
But gr8 that it's fixed :+1:

**Comment by bugwelle** [comment] 2020-03-28 16:00
Thanks. :-)

I originally planned to do some major internal changes (see for example) #892 but seeing all of these bugs I think I'll release a bugfix version first. Maybe next week or the week after that. Thank you again for reporting this (really stupid) bug.
