### ISSUE TITLE
MediaElch Coridian saves movie art for Movie X under Movie Y

### ISSUE THREAD

**Issue by zacharyfreeman70** [Komet/MediaElch#1409] opened 2022-02-06 18:52 UTC
**Describe the bug**
When a handful of movies are scraped at a time (anywhere between 0-9) MediaElch will regularly save artwork for one scraped movie in the set under the directory of another. There does not seem to be a pattern for which movies will get their artwork overwritten by another (i.e, it's not always the last one that was selected in the group nor the first, it doesn't appear to be alphabetical). This happens even when the program does not crash as described in #1408.

What's particularly annoying is that this corruption happens silently (i.e., you don't have any indication that you've got the wrong art work saved for the wrong movie until you later import the movie into Kodi).

**To Reproduce**
1. Start MediaElch
2. Specify directory to scan.
3. Shift-click to highlight 0-9 movies (to avoid triggering issue 1408).
4. Right-click group and select "Load Information"
5. On the "Movie Multi Scrape" dialogbox, Scraper: is set to "The Movie DB". Under "Infos to load" everything is checked except Tags. Automatically save each movie after scraping is unchecked. Update only movies with IMDb ID/TMDb Id is unchecked.
6. Click "Start Scraping"
7. Scrape completes. But when you select a specific movie, you'll see the incorrect artwork has been saved.

**Expected behavior**
I expected the right artwork for the right movie to be scraped and saved in the right location.

**Screenshots**
![incorrect_scrape](https://user-images.githubusercontent.com/89719708/152696502-bf8cff99-1a76-4b40-b65f-f78e3596a4fd.PNG)
You can see above that MediaElch saved the artwork for the 2019 fantasy film _Abigail_ into the 2001 Will Smith biopic _Ali_. Annoyingly, it left the Abigail entry above unscraped. Everything from _Abduction_ to _All My Life_ was shift-highlighted and scraped at the same time.

**MediaElch Version:**
 - [ ] 2.8.15-dev (nightly)
 - [x] 2.8.14 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
It honestly seems like something is broken with whatever's handling the paralellism/threading of either accessing the data or saving the data. I'm able to scan movies 1-by-1, but for hundreds of movies, that will take forever. For what it's worth I have a slow internet connection and slow storage speed, so maybe there's a race condition here as well.

**Comment by bugwelle** [comment] 2022-02-15 18:26
Oh... Thank you very much for bringing this up! Looks like a race condition...

**Comment by bugwelle** [comment] 2022-02-19 16:48
This is related to #1408

I found at least one bug (and fixed it locally) so that at least MediaElch no longer crashes. However, the mismatch could still happen. Will investigate.

Thank you very much for bringing this up!

**Comment by bugwelle** [comment] 2022-02-22 18:16
Reproducible with commit 2e1c3df546fa73ada177938d4b8f0bcf05c43ac2

Not reproducible with local fix. Will open a PR shortly. I noticed another issue that needs fixing first as well.

**Comment by bugwelle** [comment] 2022-02-27 15:22
Should be fixed by #1423 :-)

**Closed** 2022-02-27 15:22 UTC
Labels: bug, priority: high, component: movies

**Comment by zacharyfreeman70** [comment] 2022-04-01 02:59
Just downloaded the newest 2.8.16 release to test this fix. It works! Thank you for taking a look.

In my opinion, MediaElch continues to offer the best/cleanest user experience out of all the media managers out there, and that great user experience extends all the way back to the developers working on it.

Please keep up the awesome work, @bugwelle!
