### ISSUE TITLE
IMDB Episode Overivew missing

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1751] opened 2024-05-30 14:08 UTC
It seems the episode overview is missing for the IMDB Episodes the tv show overview scrapes same with episode picture ratting tv rating excetra just the overview is missing from the scraping process.

**Comment by bugwelle** [comment] 2024-06-01 09:49
This is likely a duplicate of https://github.com/Komet/MediaElch/issues/1724

I didn't publish an official release, yet.

If you're on Windows or Linux, you can use the latest snapshot version from https://mediaelch-downloads.ameyering.de/snapshots/

Regards,
Andre

**Comment by kolbdog323** [comment] 2024-06-04 19:44
Actually it's missing again it was working a few builds ago but now they are missing again. That is why i created a new issue since the old issue was closed. It was working but now its not again i use the nightly builds.

**Comment by kolbdog323** [comment] 2024-06-09 05:28
Any response?

**Comment by kolbdog323** [comment] 2024-06-10 12:18
I just tested it on All in the Family: S01E01 Meet The Bunkers. No episode plot. Here is a screenshot that shows the issue adn a screenshot that shows i have the latest version.
![2](https://github.com/Komet/MediaElch/assets/161794176/62f1d03c-5895-4f94-a7a5-2c687ee51b11)
![1](https://github.com/Komet/MediaElch/assets/161794176/1234e724-a33f-4f69-a80d-d3b210f41a2a)

**Comment by bugwelle** [comment] 2024-06-13 05:43
Thanks! 

Link: https://www.imdb.com/title/tt0509891/?ref_=ttep_ep1

**Comment by kolbdog323** [comment] 2024-06-14 18:28
> Thanks!
> 
> Link: https://www.imdb.com/title/tt0509891/?ref_=ttep_ep1

Any luck in reproducing the issue or fixing it?

**Comment by kolbdog323** [comment] 2024-06-15 16:43
Wasn't workign for while but working again. SOrry for posting the issue.

**Comment by kolbdog323** [comment] 2024-06-15 16:47
Also it won't scrape imdb episode overview for every episode just some of them.

**Comment by kolbdog323** [comment] 2024-06-15 17:06
Sorry reason i keep mentiong imdb issues is becasue i use all 3 scrapers i dont use the custom one i use all 3 indiuvally I just prefer imdb for certain shows.

**Comment by bugwelle** [comment] 2024-06-17 18:11
Hi,

sorry for the delay. Please see https://github.com/Komet/MediaElch/issues/1710 for reasons why. :)

I've identified the issue and will fix this issue shortly. I've added tests to ensure that it keeps working in the future.

Regards,
Andre

**Comment by bugwelle** [comment] 2024-06-17 18:16
A new nightly version should be available withing the next 1h.

**Closed** 2024-06-17 18:15 UTC
Labels: component: scraper, duplicate
