### ISSUE TITLE
NameFormatter: Words-to-exclude ignore words with dots

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#1131] opened 2020-12-27 16:24 UTC
**Describe the bug**
I might finally have became fully senile but since jumping to the latest stable and nightlies the "Words to exclude" seems to be broken. I had added so much stuff that as far as I can remember more or less every title was perfectly cleaned up but now they are all cluttered.

Seems that the excluded words are compared to the cleaned up title where the dots are removed resulting in a miss match.

**To Reproduce**
1. Add DL.DD5.1.H.264 in excluded words
2. Have a movie including the above a hit scrape
3. Movie name is shown as 'Movie DL DD5 1 H 264'

**Expected behavior**
That the excluded words are compared to the not cleaned up title.

**MediaElch Version:**
 - [X] 2.8.3-dev (nightly)
 - [ ] 2.8.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
Would it be possible to make use of the filename instead of the folder name? Because I always clean that up when adding it to my share so would simplify things.
Or maybe make it possible to put strings of text in excluded words?

**Comment by bugwelle** [comment] 2020-12-27 17:43
This was a bugfix with side-effects apparently... The issue was that the "words" to exclude were actually interpreted as a regular expression, meaning that e.g. `abc(` wouldn't work because it is an invalid regular expression. In `DD5.1` the dot was interpreted as the "any"-character.

In the worst case that I tested, this resulted in MediaElch not responding at all for several minutes (because the regular expression matcher tried to match everything).

Due to some really bad regression I had to make a patch release (v2.8.2) which also contained my not-yet-finished fix for the "excludeWords" feature.

**Comment by bugwelle** [comment] 2020-12-27 17:54
By the way: The reason the word was transformed into a regular expression was that then we can replace prepending dashes, underscores, ... as well.

I've now switched the behavior in the first place. #1132 will now simply replace the word with `""`, i.e. will remove it. I should have done so in the first place but forgot it.

I'm sorry for this annoyance. Thank you very much for reporting this issue!

**Comment by bugwelle** [comment] 2020-12-27 17:59
I will release a new Nightly for Windows. Should be available in about an hour.

**Comment by psonnosp** [comment] 2020-12-27 18:56
You're the one to thank as usual 👍🏻

**Comment by psonnosp** [comment] 2020-12-28 22:25
That partially worked.

But it seems to have made the words to exclude sensitive to placement among each other in a way I don't think it was before.
So Movie.WEB-DL will become Movie-DL if WEB is placed before WEB-DL in words to exclude and don't think this was the case in earlier versions.

Sure I can begin from scratch with the exclude list and maybe make it work with some trial and error and figure out all the possible combinations but would it be a big job for you to make it an option for ME to look at the filename instead of the folder name?

**Comment by bugwelle** [comment] 2020-12-29 09:02
> Some words have become case sensitive, and some wont match no matter the case.
This is so confusing trying to setup 😄

Will look into it. :-)

I forgot about case-insensitivity... Thank you for reminding me. That will be fixed ASAP.

> But it seems to have made the words to exclude sensitive to placement among each other in a way I don't think it was before.
So Movie.WEB-DL will become Movie-DL if WEB is placed before WEB-DL in words to exclude and don't think this was the case in earlier versions.

hmmm... I could sort the exclude-words by length. That would work in your specific case. I'll just give it a try and will upload a new nightly for Windows in about an hour. :-)

**Comment by bugwelle** [comment] 2020-12-29 09:16
Fixed by https://github.com/Komet/MediaElch/commit/b22a0c5b5c9a6a87cc9cc85a4d25eb2a04aae4d5
Tests and another improvement in https://github.com/Komet/MediaElch/commit/38277d21cf85dd34811a5457510c68d52458313e

Sorting was already done so I would expect "WEB-DL" to be replaced before "WEB". Could you test it with the next nightly? :-)

**Closed by bugwelle** 2020-12-29 09:16 UTC
Labels: bug
