### ISSUE TITLE
Proxy not reenabled after dropping it for a kodi sync

### ISSUE THREAD

**Issue by b-m-f** [Komet/MediaElch#1446] opened 2022-07-02 18:14 UTC
https://github.com/Komet/MediaElch/blob/939a2db59aa7d3408f6f7bc48ceaa82aa3362707/src/ui/media_centers/KodiSync.cpp#L48

Is this the destroyer that cleans up the sync after it was succesfully initiated?

How about a adding new enableProxy method like https://github.com/Komet/MediaElch/blob/939a2db59aa7d3408f6f7bc48ceaa82aa3362707/src/network/NetworkManager.cpp#L19 and then adding it to restart the proxy in that destroyer function? 

The `enableProxy` function can use from https://github.com/Komet/MediaElch/blob/af9b1648ce2f84f92aa36fdf6d8e0685d3673071/src/settings/NetworkSettings.cpp#L151 if I understand the code correctly.

It could also be moved into `src/network/NetworkManager.cpp` for a refactor if that idea makes sense.

**Comment by bugwelle** [comment] 2022-07-19 17:28
Hi,

thank you for reporting this issue. Just so that I understand, what is the order of events?

1. "Use Proxy for Kodi" is disabled in Network Settings
2. Kodi Sync is executed
3. "Use Proxy for Kodi" is enabled in Network Settings
4. Kodi Sync is executed, proxy is _not_ used

Could you clarify the steps above? :-)

**Comment by bugwelle** [comment] 2022-07-30 14:05
Closing for now, as #1449 is merged. Please respond to this issue and I'll re-open in case that the issue persists. :-)

**Comment by b-m-f** [comment] 2022-07-30 15:43
Hey there,

just got time to check this, also a lot of happening on my side :) . The issue was as follows:

1. Enable proxy and "Use Proxy for Kodi" is disabled in Network Settings
2. Use mediaelch functionality which will go through the proxy
3. Sync with Kodi
4. Use mediaelch functionality again, but now the proxy is still disabled


Ill give the new version a try, but looking at the code that changed I believe that the issue still persists as the proxy seems to get disabled globally when doing the Kodi sync, without reenabling it afterwards

**Comment by bugwelle** [comment] 2022-07-30 16:52
> Use mediaelch functionality again, but now the proxy is still disabled

Ah, thanks! Will look into it.

**Comment by bugwelle** [comment] 2022-08-21 14:26
@b-m-f With #1458 I fixed at least one issue with the proxy. The Qt documentation was not very clear...
I didn't reproduce your steps, yet. Step (4): Is the proxy disabled for Kodi Sync or for (movie) scraping?

**Comment by bugwelle** [comment] 2022-12-26 13:24
Closing due to inactivity. Can't reproduce it (anymore). Please let me know if the issue appears again.

Regards,
Andre

**Closed by bugwelle** 2022-12-26 13:24 UTC
Labels: bug, kodi
