### ISSUE TITLE
Space between columns

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#975] opened 2020-05-09 13:23 UTC
Space between columns

I don't know if it's a bug, but ...
It seems that the space between the columns has increased.

See here https://i.imgur.com/TcUquZA.jpg  

EDIT: Windows 10

**Comment by bugwelle** [comment] 2020-05-10 07:43
Duplicate of https://github.com/Komet/MediaElch/issues/793

I tried to fix this one afternoon but wasn't able, yet. This happened because of an Update of Qt (our GUI framework). Couldn't figure out how to revert this behavior change, yet. :/

**Closed by bugwelle** 2020-05-10 07:43 UTC
Labels: feature request

**Comment by ticao2** [comment] 2020-05-11 01:46
a thousand apologies
I did not imagine that the problem of the space of the icons was the same problem of the space of the columns.

**Comment by bugwelle** [comment] 2020-05-11 06:15
> a thousand apologies

No need to apologize at all. Background: Each icon is inside a separate column. For some reason, newer Qt versions added some spacing and I didn't figure out how to remove that, yet.

**Comment by bugwelle** [comment] 2021-03-31 16:39
Will be fixed by  #1266
