### ISSUE TITLE
Preview window error with dual monitors

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#863] opened 2020-01-09 03:04 UTC
**Describe the bug**
If you on a two monitor setup have ME open on the secondary monitor and click on the magnifying glass to view an image in full size the image seems to open somewhere off screen.

**To Reproduce**
1. Open ME, move and maximize it on the secondary monitor.
2. Click to open a TV-show.
3. Click on the magnifying glass of a fanart of choice.
4. Image opens somewhere out of sight and only thing to do is to hit Esc to close it.

**Expected behavior**
The preview window should open up inside ME and not somewhere you can't see it.

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by bugwelle** [comment] 2020-01-10 10:57
MediaElch uses Qt which allows us to store the window positions. If one dialog or other window has been opened on monitor 1 (or has been dragged there) then it will open there the next time as well regardless of where MediaElch itself (i.e. the main window) is positioned. This has been an issue in the past as well.

Maybe we can use https://doc.qt.io/qt-5/qguiapplication.html#screens or similar to avoid this issue.

**Comment by psonnosp** [comment] 2020-01-10 21:44
No that's not what happens.
This is how I have my screens:
![Image7](https://user-images.githubusercontent.com/28609335/72188034-9c471980-33f9-11ea-8b75-9bdf299abef2.jpg)
2 is my main display and if I open ME there everything works as it should but when I move or open ME in 1 the preview window is open outside to the right of 1, at least that's where my pointer flies away to for placing itself on the close button.
Same thing happens if I try to do what you say should happen, to open ME in 2 and click for a preview window and then move the preview window to 1. When I then move ME to 1 and once again open a preview window it opens up somewhere outside of 1 to the right.

**Comment by bugwelle** [comment] 2020-01-11 19:48
Very strange behavior. Thank you for explaining it. This will take some time to debug as I don't have a Windows system except for a virtual machine.

**Comment by psonnosp** [comment] 2020-01-12 01:27
And just to add to the confusion, If I change place of 1 and 2 in display settings and do the same the preview window opens up off screen to the left of 1.
This is in no way a big problem, just thought I should report it since I found it, so save this one to a rainy day when there's nothing else to do ;)

**Comment by psonnosp** [comment] 2020-01-20 02:37
The position for this window doesn't seem to be saved, if ME is maximized it always open up in the center of the screen no matter where you place it before closing it.
And it gets really interesting when you don't have ME maximized and open it. The further to the right of the screen you move the main window the preview window opens up like ten times that even further to the right. So seems that it's placed using an percentage offset or something from the left edge of the main window.
Some screens in case my explanation suck ;)
![Image1](https://user-images.githubusercontent.com/28609335/72694411-33684b80-3b35-11ea-8111-621f803a2d70.jpg)
![Image2](https://user-images.githubusercontent.com/28609335/72694412-33684b80-3b35-11ea-9ed5-dadff3442803.jpg)
![Image3](https://user-images.githubusercontent.com/28609335/72694413-33684b80-3b35-11ea-8675-dff0eb2c35ea.jpg)
![Image4](https://user-images.githubusercontent.com/28609335/72694414-33684b80-3b35-11ea-9966-06cda29d65f2.jpg)

To reproduce, ME not maximized, select a TV-show, open a preview then close it. Move ME a little to the right and notice the difference.

**Comment by bugwelle** [comment] 2020-04-11 18:16
Confirmed. I checked the code and happens due to these lines:

```cpp
    int xMove = (parentWidget()->size().width() - size().width()) / 2;
    QPoint globalPos = parentWidget()->mapToGlobal(parentWidget()->pos());
    move(globalPos.x() + xMove, globalPos.y());
```

Code has been that way since 2012-07-25 (https://github.com/Komet/MediaElch/issues/29)

The documentation of `QDialog::move` says:

> This property holds the position of the widget within its parent widget

Well the code assumes global coordinates. Correct code would look like:

```cpp
    int xMove = (parentWidget()->size().width() - size().width()) / 2;
    move(parentWidget()->x() + xMove, parentWidget()->y());
```

I'll fix this with a PR soon. :smiley:

**Comment by bugwelle** [comment] 2020-04-11 18:28
The same goes for the normal image dialog. Will be fixed as well.

**Closed** 2020-04-11 19:32 UTC
Labels: bug, ui
