### ISSUE TITLE
Renamed .tmp files are left in place of real files during rename

### ISSUE THREAD

**Issue by vegright** [Komet/MediaElch#1345] opened 2021-06-22 04:38 UTC
**Describe the bug**
During a rename, I found that if the filename's only difference is capitalization cause this issue.  Seems (guessing here) that during rename the files are intermediately renamed to *.tmp (though there are files left in recycle directory).  Error happens, and .tmp files are left in place of original files. 

In my case I had 2 files:
Killing Eve - S01E05 - I Have **A** Thing About Bathrooms.mkv
Killing Eve - S01E06 - Take Me **T**o **T**he Hole!.mkv
Should have been renamed to:
Killing Eve - S01E05 - I Have **a** Thing About Bathrooms.mkv
Killing Eve - S01E06 - Take Me **t**o **t**he Hole!.mkv
But instead I got:
Killing Eve - S01E05 - I Have a Thing About Bathrooms.mkv.tmp
Killing Eve - S01E06 - Take Me to the Hole!.mkv.tmp

Note, the .nfo and .jpg files also had .tmp extensions added.  This has been going on for a while (at least a couple of minor versions), I just got around to diagnosing the issue.

**Screenshots**
I captured a screenshot of [rename dialog and file system](https://drive.google.com/drive/folders/1voQpv7XX99HO-MtN9YsUbOkN7FWZCuN-?usp=sharing) afterward.

**MediaElch Version:**
 - [ ] 2.8.12 stable

**Operating System:**
 - [ ] Linux (distribution: openSUSE LEAP 15.3)

**Additional context**
Files are on a NAS, and mounted using CIFS.  So could be CIFS specific or Linux.  I tested on Windows with same MediaElch version, and did not have the same issue.

I'm only using Linux with MediaElch due to the library size, and the rescan takes forever on Windows.  That and the interface is tons slower on windows.

**Comment by bugwelle** [comment] 2021-06-22 11:23
Thanks. I'll mark this as a duplicate of https://github.com/Komet/MediaElch/issues/1281 as it's also about "renamer" cleanup. :)


Please note that I currently do not have a lot of time, see https://github.com/Komet/MediaElch/issues/1344 . :)

**Closed by bugwelle** 2021-06-22 11:23 UTC

**Comment by bugwelle** [comment] 2021-06-22 11:25
Oh, btw, your screenshots don't contain `.tmp` files. Did you delete them by hand? :)

**Comment by vegright** [comment] 2021-06-22 22:22
If you look at S01E05 and S01E06 for mkv, nfo, and jpg files, they all 
have .tmp extensions.  Sorry, should have mentioned that in the 
description.

Eric


------ Original Message ------
From: "Andre Meyering" ***@***.***>
To: "Komet/MediaElch" ***@***.***>
Cc: "vegright" ***@***.***>; "Author" 
***@***.***>
Sent: 6/22/2021 6:25:52 AM
Subject: Re: [Komet/MediaElch] Renamed .tmp files are left in place of 
real files during rename (#1345)

**Comment by bugwelle** [comment] 2021-06-23 10:30
Oh, didn't see that
Thanks :)
