### ISSUE TITLE
Could you please implement some basic functionality

### ISSUE THREAD

**Issue by ccpf** [Komet/MediaElch#1500] opened 2022-12-17 11:00 UTC
Hi, I have been using tiny media manager till now but since development of the free version has stopped and the last free version is rather buggy, I have been looking for alternatives and came across media elch. 
Compared to tinyMM I really like the much faster start up time (I am using it on a mini PC attached to my TV where tiny MM would take a whopping 2 minutes to start compared to 15 seconds of media elch). However, I still find myself using tiny MM as I found that some rather basic functionality is missing from media elch which I am listing below. Perhaps you could consider implementing this as your time allows. Thank you.

- The media table is lacking some very crucial information like the year of the movie and its rating. Plus, the table should have clickable column headings so the table can be quickly sorted based on, for instance, movie name, year, or rating. 
- Ticking the feature to disregard articles in the movie name, like "the", for the alphabetical sorting of movies misclassifies "Die" as an article. So "Die Hard" for instance, appears under "H" (?!?). 
- About 1/3 of the the screen space is wasted with fan art. I would suggest to simply show the main movie poster and remove the rest.
- Considering that most people will be using this software at night, either connected to the TV or a larger screen, dark mode should be the standard or at least available.
- The user should be able to change some basic display parameters like "font size" as a lot of content is basically illegible, at least for the distance I am sitting from my TV. 
- Actor images are not shown.
- Scraping from IMDB does not seem to work.
- Foreign movies appear to be scraped in their original language (the title), which can make them hard to find if you only know them by their English title.

All the above are features that tiny MM has as a standard, so perhaps you could take a look at their layout (version 3). It is nice an clean. What you do better, apart from the programme running much faster overall, is that you can more easily find movies by genre and you allow movies to be labelled.
Another features that would be very useful is: make actor names clickable, so that when you click them, you get a list of all their movies in your db.

OK, thanks again for providing the software free of charge and keep up the good work.
Pete

**Comment by bugwelle** [comment] 2022-12-17 13:09
Hi there,

thanks for opening giving feedback. It's always appreciated. :smile:

I'm the current maintainer (since 2018). I mostly do bug-fixes, since I've only got limited time, see ["Office Hours"](https://github.com/Komet/MediaElch/issues/1417).

I'll go through your points line by line:

>    The media table is lacking some very crucial information like the year of the movie and its rating. Plus, the table should have clickable column headings so the table can be quickly sorted based on, for instance, movie name, year, or rating.

MediaElch doesn't have a "proper table". I thought about having an Excel-like table for movies, that is sortable, but never got to implement that.

>    Ticking the feature to disregard articles in the movie name, like "the", for the alphabetical sorting of movies misclassifies "Die" as an article. So "Die Hard" for instance, appears under "H" (?!?).

Per default, English, German, Portuguese, French, and Spanish articles are ignored. That includes `Die`. You can change that in `advancedsettings.xml`, see https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings

https://github.com/Komet/MediaElch/blob/master/docs/advancedsettings.xml#L68-L117

I would like to move most of those settings to the UI sometime in the future. I think `advancedsettings.xml` was created, because Kodi/XBMC has one as well, with many of the same tags.


>    About 1/3 of the the screen space is wasted with fan art. I would suggest to simply show the main movie poster and remove the rest.

Do you refer to these?

![Screenshot_20221217_135027](https://user-images.githubusercontent.com/1667306/208242776-74c1d107-058f-4caa-8a2e-82968415249b.png)

If the window becomes too small, it should move to one column instead of two. Out of curiosity: What screen resolution do you use?

 >   Considering that most people will be using this software at night, either connected to the TV or a larger screen, dark mode should be the standard or at least available.

That was requested in https://github.com/Komet/MediaElch/issues/761
Design is not my best strength. :smile: 
The main window is a custom UI. If I were to write MediaElch from scratch, I probably wouldn't use that. Changing the UI is rather difficult, so I never really tried it (because of all the customizations). The settings-window are default Qt-Widgets and work with dark themes, see https://mediaelch.github.io/mediaelch-blog/posts/mediaelch-v2.6.0/#ui-linux

>    The user should be able to change some basic display parameters like "font size" as a lot of content is basically illegible, at least for the distance I am sitting from my TV.

Do you happen to have a 4k screen or use display scaling >100%?
The next MediaElch version will support 4k scaling, see https://github.com/Komet/MediaElch/issues/429#issuecomment-1312743005
If you download a MediaElch "Nightly" version for Windows 10 or 11 from https://mediaelch.github.io/mediaelch-doc/download/windows.html#download-mediaelch-for-windows , this should already work.

>   Actor images are not shown.

Do actor images exist? Tested locally (on Linux) and it seems to still work. What system do you use? :)

![Screenshot_20221217_140355](https://user-images.githubusercontent.com/1667306/208243239-440fb4fd-e180-4af5-ac84-aa8ccc027b1d.png)

>  Scraping from IMDB does not seem to work.

Argh... I can confirm that following is broken in the IMDb scraper:

- TV/movies: runtime

What else does not work? :)

>  Foreign movies appear to be scraped in their original language (the title), which can make them hard to find if you only know them by their English title.

Is that for IMDb? Yeah, as far as I can see, IMDb does not allow to select a language on their site unless you have an account. If you know a trick on how to change the site's language, please let me know. :)

> Another features that would be very useful is: make actor names clickable, so that when you click them, you get a list of all their movies in your db.

Thanks for this proposal. :)

Kind regrads,
Andre

**Comment by danilovesky** [comment] 2022-12-22 18:25
Came to report the issue with sorting of "Die Hard" title (looks like a popular movie before Christmas) and was glad to find the `advancedsettings.xml` solution that works a treat.

As an added benefit, it was interesting to read @bugwelle informative response to all these feature requests :)

**Comment by ccpf** [comment] 2022-12-23 10:01
Thanks for your prompt reply Andre. Here some responses to you questions:

> > The media table is lacking some very crucial information like the year of the movie and its rating. Plus, the table should have clickable column headings so the table can be quickly sorted based on, for instance, movie name, year, or rating.
> 
> MediaElch doesn't have a "proper table". I thought about having an Excel-like table for movies, that is sortable, but never got to implement that.

OK I see. Bummer. Although such a table would greatly enhance the use experience IMHO, especially if you add the year and rating columns.

> Per default, English, German, Portuguese, French, and Spanish articles are ignored. That includes `Die`. You can change that in `advancedsettings.xml`, see https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings
> 
> https://github.com/Komet/MediaElch/blob/master/docs/advancedsettings.xml#L68-L117

OK thanks. I got that sorted.

> > > About 1/3 of the the screen space is wasted with fan art. I would suggest to simply show the main movie poster and remove the rest.
> 
> Do you refer to these?
> 
> ![Screenshot_20221217_135027](https://user-images.githubusercontent.com/1667306/208242776-74c1d107-058f-4caa-8a2e-82968415249b.png)

Yes I meant those. Seems a bit overkill to show them all on the main screen. They could be hidden behind a tab for instance.

> If the window becomes too small, it should move to one column instead of two. Out of curiosity: What screen resolution do you use?

On my screen they are in 2 columns and take up about 1/3 of the screen. Which seems a waste. My TV is fairly old so only has like 1280x720px and I am sitting about 2m away from it, which, at least for me, makes the text difficult to read. Hence my comment that the font-size should be adjustable.

> That was requested in #761 Design is not my best strength. 😄 The main window is a custom UI. If I were to write MediaElch from scratch, I probably wouldn't use that. Changing the UI is rather difficult, so I never really tried it (because of all the customizations). The settings-window are default Qt-Widgets and work with dark themes, see https://mediaelch.github.io/mediaelch-blog/posts/mediaelch-v2.6.0/#ui-linux

I see. I am on Windows unfortunately so do not have access to the dark theme.

> Do you happen to have a 4k screen or use display scaling >100%? The next MediaElch version will support 4k scaling, see [#429 (comment)](https://github.com/Komet/MediaElch/issues/429#issuecomment-1312743005) If you download a MediaElch "Nightly" version for Windows 10 or 11 from https://mediaelch.github.io/mediaelch-doc/download/windows.html#download-mediaelch-for-windows , this should already work.

Nope, only 1280x720 (see above).

> > > Actor images are not shown.
> 
> Do actor images exist? Tested locally (on Linux) and it seems to still work. What system do you use? :)

I have a miniPC with Win 11 attached to my TV where I only get empty placeholders instead of the actual images. 
 
> > Scraping from IMDB does not seem to work.
> 
> Argh... I can confirm that following is broken in the IMDb scraper:
> 
>     * TV/movies: runtime

In my case, it is not just the runtime but the entire movie. If I try to scrape it in TMDB it works just fine, if I try to scrape it in IMDB the search (for the movie title) comes up empty, i.e., it does not find the movie. Maybe I am doing sth wrong?!

> What else does not work? :)

Sorry, but for now I have gone back to tiny media manager due to the font legibility and dark theme issues which make media elch difficult to use for me, especially at night. 

> > > Foreign movies appear to be scraped in their original language (the title), which can make them hard to find if you only know them by their English title.
> 
> Is that for IMDb? Yeah, as far as I can see, IMDb does not allow to select a language on their site unless you have an account. If you know a trick on how to change the site's language, please let me know. :)

Since IMDB scraping does not work for me, this was with TMDB. Again, maybe I did not choose the correct setting somewhere.

Thanks again and good luck with the project ... 
Pete

**Comment by bugwelle** [comment] 2022-12-23 13:51
Hi,

> Yes I meant those. Seems a bit overkill to show them all on the main screen. They could be hidden behind a tab for instance.

I think it depends on what your goal is: In my case, I always wanted to have images (posters), and didn't care too much about other metadata. So I liked the rather large image side bar. But I think a splitter for the sidebar could be useful (splitter -> similar to how you can resize the movie table width, just for the image sidebar).

> On my screen they are in 2 columns and take up about 1/3 of the screen… Hence my comment that the font-size should be adjustable.

Thanks! I have to check this again in January when I'm back home, but doesn't Windows have an adjustable fontsize? I have never tested it on MediaElch, so don't know if that works, but I would hope that Windows's font size is used.

> Nope, only 1920x1080 (see above).

I should have been more precise: MediaElch's current Windows release does not handle scaling well, i.e. it only supports 100%. The next version (and current Nightlies) for Windows 10 will support scaling. This was found on 4k displays first, because many users have scaling >100% on 4k displays. :)

> I have a miniPC with Win 11 attached to my TV where I only get empty placeholders instead of the actual images.

Do you have an example? i.e. movie name + scraper you use? :)

> In my case, it is not just the runtime but the entire movie. 

Movie and TV show search is broken for IMDb... Argh. Will be fixed soon.

> Sorry, but for now I have gone back to tiny media manager due to the font legibility and dark theme issues which make media elch difficult to use for me, especially at night.

Understandable. :)
TMM has more features as well. I appreciate that you tried MediaElch and reported features that you feel are missing!

Regards,
Andre

**Comment by ticao2** [comment] 2022-12-24 17:24
**Dreams and Wishes**
Looks like @ccpf  uses it the same way I do.
I would like something to be used by older people without knowledge.
Many years ago I suggested something like this:

**Opening**
![MediaElch Proposta Teste 05 Abertura](https://user-images.githubusercontent.com/21062440/209445177-5ac13f7e-6364-4f21-9dfe-989f539aa8ed.jpg)

**Filtering**
![MediaElch Proposal Select   Watch 2](https://user-images.githubusercontent.com/21062440/209445248-993a6476-3963-4d26-b7d0-f40eabf43bb8.jpg)

**Search and Play**
![MediaElch Proposal Select   Watch 3](https://user-images.githubusercontent.com/21062440/209445253-b3aa4c3d-85c0-431c-ab40-7a7f1d18cd3b.jpg)

Today I would do it a little differently.
I wouldn't put Fanart on the screen.

It might be easier to generate a standalone executable, something like "**MediaElchSP.exe**" or **Search and Play**, which uses the existing database.

TMDb always uses the **original language** for the **Original Title**.
Undoubtedly, for Iranian, Japanese, Korean films etc... everything is very difficult.

As for IMDB, I gave up a while ago. More than 8 years.
Seems like they change something every 3 months and everything stops working right.

**Comment by bugwelle** [comment] 2022-12-28 17:35
Regarding Dark Theme: I've added an experimental dark theme: https://github.com/Komet/MediaElch/issues/761#issuecomment-1366813816

**Comment by bugwelle** [comment] 2024-01-24 18:41
Closing: I don't have the time for feature requests anymore, and because this is a rather unspecific PR-title, other issues will get higher priority. See #1710 for details.

**Closed by bugwelle** 2024-01-24 18:41 UTC
Labels: feature request
